"""Cursor platform adapter."""

from __future__ import annotations

from pathlib import Path

from cataforge.platform.base import PlatformAdapter
from cataforge.platform.helpers import symlink_or_copy


class CursorAdapter(PlatformAdapter):
    @property
    def platform_id(self) -> str:
        return "cursor"

    @property
    def display_name(self) -> str:
        return "Cursor"

    def get_project_root_env_var(self) -> str | None:
        return "CURSOR_PROJECT_DIR"

    def get_agent_scan_dirs(self) -> list[str]:
        # Default: Cursor-native only. The legacy fallback to ``.claude/agents``
        # was removed in the M5 change — only ``scan_dirs[0]`` is ever written
        # during deploy, so listing ``.claude/agents`` as a fallback created
        # the false impression that Cursor deploy would produce artifacts
        # under ``.claude/``. Users who really want ``.claude/agents`` scanned
        # can still declare it explicitly in their profile.yaml.
        return list(
            self._profile.get("agent_definition", {}).get(
                "scan_dirs", [".cursor/agents"]
            )
        )

    def get_agent_format(self) -> str:
        return "yaml-frontmatter"

    def deploy_additional_outputs(
        self, rules_dir: Path, project_root: Path, *, dry_run: bool = False
    ) -> list[str]:
        return self._generate_mdc_rules(rules_dir, project_root, dry_run=dry_run)

    def deploy_rules(
        self, source_dir: Path, project_root: Path, *, dry_run: bool = False
    ) -> list[str]:
        """Rule deployment for Cursor.

        The canonical Cursor rule surface is ``.cursor/rules/*.mdc``, which
        is generated by ``deploy_additional_outputs`` elsewhere. This method
        only governs the **optional** Markdown mirror at ``.claude/rules``
        intended for projects that also run Claude Code against the same
        tree and want to share source-of-truth prompts.

        The mirror is **off by default** (as of the M5 change).  Opt in via
        ``rules.cross_platform_mirror: true`` in
        ``.cataforge/platforms/cursor/profile.yaml`` — or a user-level
        ``platforms/cursor/overrides/profile.yaml`` if the registry supports
        overrides on your install.
        """
        rules_cfg = self._profile.get("rules") or {}
        if not bool(rules_cfg.get("cross_platform_mirror", False)):
            if dry_run:
                return [
                    "SKIP: .claude/rules Markdown mirror "
                    "(enable via profile rules.cross_platform_mirror: true)"
                ]
            return []
        actions = symlink_or_copy(
            source_dir, project_root / ".claude" / "rules", dry_run=dry_run
        )
        note = (
            "note: Cursor deploy linked .claude/rules for cross-platform prompt "
            "sharing (profile rules.cross_platform_mirror=true)"
        )
        if dry_run:
            return actions + [note]
        return actions + [note]

    def _generate_mdc_rules(
        self, source_dir: Path, project_root: Path, *, dry_run: bool = False
    ) -> list[str]:
        """Generate .cursor/rules/ MDC files from Markdown sources."""
        output_dir = project_root / ".cursor" / "rules"
        if not dry_run:
            output_dir.mkdir(parents=True, exist_ok=True)

        actions: list[str] = []
        overrides_dir = (
            project_root / ".cataforge" / "platforms" / "cursor" / "overrides" / "rules"
        )

        for md_file in sorted(source_dir.glob("*.md")):
            mdc_name = md_file.stem + ".mdc"
            if dry_run:
                actions.append(f"would deploy rules/{md_file.name} → .cursor/rules/{mdc_name}")
                continue
            content = md_file.read_text(encoding="utf-8")
            mdc_content = _wrap_as_mdc(md_file.stem, content)
            (output_dir / mdc_name).write_text(mdc_content, encoding="utf-8")
            actions.append(f"rules/{md_file.name} → .cursor/rules/{mdc_name}")

        if overrides_dir.is_dir():
            for md_file in sorted(overrides_dir.glob("*.md")):
                mdc_name = md_file.stem + ".mdc"
                if dry_run:
                    actions.append(
                        f"would deploy overrides/{md_file.name} → .cursor/rules/{mdc_name}"
                    )
                    continue
                content = md_file.read_text(encoding="utf-8")
                mdc_content = _wrap_as_mdc(md_file.stem, content)
                (output_dir / mdc_name).write_text(mdc_content, encoding="utf-8")
                actions.append(f"overrides/{md_file.name} → .cursor/rules/{mdc_name}")

        return actions

    def _mcp_json_path(self, project_root: Path) -> Path:
        return project_root / ".cursor" / "mcp.json"


def _wrap_as_mdc(name: str, content: str) -> str:
    """Wrap Markdown content with MDC frontmatter for Cursor."""
    frontmatter = f"""---
description: "{name} rules"
globs:
alwaysApply: true
---
"""
    return frontmatter + content
