#!/usr/bin/env python3
"""setup_penpot.py — CataForge Penpot 完整部署工具 (Python)

Plan A 架构: Docker Compose 部署 Penpot 本体 + npx 启动 MCP Server。

子命令:
  deploy       完整部署: Penpot (Docker) + MCP Server (npx)
  mcp-only     仅启动 MCP Server (假设 Penpot 已运行)
  start        启动已部署的服务 (Penpot + MCP)
  stop         停止所有服务
  status       查看服务状态
  --ensure     快速模式: 检测已运行则退出，否则启动

用法:
  python .claude/scripts/setup_penpot.py deploy      # 完整部署
  python .claude/scripts/setup_penpot.py mcp-only    # 仅 MCP
  python .claude/scripts/setup_penpot.py start       # 启动服务
  python .claude/scripts/setup_penpot.py stop        # 停止服务
  python .claude/scripts/setup_penpot.py status      # 查看状态
  python .claude/scripts/setup_penpot.py --ensure    # 快速检查/启动

环境变量 (可选覆盖，可写入 .env):
  PENPOT_INSTALL_DIR          Penpot Docker Compose 目录 (默认: ~/penpot-docker)
  PENPOT_PORT                 Penpot 前端端口 (默认: 9001)
  PENPOT_MCP_SERVER_PORT      MCP Server 端口 (默认: 4401)
  PENPOT_MCP_PLUGIN_PORT      Plugin Server 端口 (默认: 4400)
  PENPOT_FLAGS                Penpot feature flags (默认: enable-login-with-password)
"""

import argparse
import json
import os
import secrets
import signal
import subprocess
import sys
import textwrap
import time
from typing import Optional

# 确保同目录的 _common 可导入
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import (
    BOLD,
    CYAN,
    DIM,
    GREEN,
    NC,
    RED,
    YELLOW,
    check_port_available,
    detect_platform,
    ensure_utf8_stdio,
    fail,
    find_project_root,
    get_command_version,
    has_command,
    info,
    is_port_listening,
    load_dotenv,
    ok,
    run_cmd,
    section,
    warn,
)

# ============================================================================
# 配置
# ============================================================================

PLATFORM = detect_platform()

# 默认端口
DEFAULT_PENPOT_PORT = 9001
DEFAULT_MCP_PORT = 4401
DEFAULT_PLUGIN_PORT = 4400

# 健康检查超时 (秒)
HEALTH_TIMEOUT = 60
MCP_HEALTH_TIMEOUT = 30

# PID 文件
MCP_PID_FILE = "/tmp/penpot-mcp-server.pid"
MCP_LOG_FILE = "/tmp/penpot-mcp-server.log"

# Docker Compose 模板 (Penpot 官方推荐配置)
DOCKER_COMPOSE_TEMPLATE = textwrap.dedent("""\
    ## Penpot Docker Compose — auto-generated by CataForge setup_penpot.py
    ## Based on: https://community.penpot.app/t/self-hosting-guide/
    ##
    ## 6 services: frontend, backend, exporter, postgres, valkey, mailcatch
    ## Ports: {penpot_port}:80 (frontend)

    networks:
      penpot:

    volumes:
      penpot_postgres_v15:
      penpot_assets:

    services:
      penpot-frontend:
        image: penpotapp/frontend:latest
        restart: always
        ports:
          - "{penpot_port}:80"
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          - penpot-backend
          - penpot-exporter
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}

      penpot-backend:
        image: penpotapp/backend:latest
        restart: always
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          - penpot-postgres
          - penpot-valkey
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
          - PENPOT_DATABASE_USERNAME=penpot
          - PENPOT_DATABASE_PASSWORD=penpot
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
          - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
          - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
          - PENPOT_TELEMETRY_ENABLED=false
          - PENPOT_SMTP_DEFAULT_FROM=no-reply@penpot.local
          - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@penpot.local
          - PENPOT_SMTP_HOST=penpot-mailcatch
          - PENPOT_SMTP_PORT=1025
          - PENPOT_SMTP_TLS=false
          - PENPOT_SMTP_SSL=false

      penpot-exporter:
        image: penpotapp/exporter:latest
        restart: always
        networks:
          - penpot
        environment:
          - PENPOT_PUBLIC_URI=http://penpot-frontend

      penpot-postgres:
        image: postgres:15
        restart: always
        stop_signal: SIGINT
        volumes:
          - penpot_postgres_v15:/var/lib/postgresql/data
        networks:
          - penpot
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=penpot
          - POSTGRES_USER=penpot
          - POSTGRES_PASSWORD=penpot

      penpot-valkey:
        image: valkey/valkey:8-alpine
        restart: always
        networks:
          - penpot

      penpot-mailcatch:
        image: sj26/mailcatcher:latest
        restart: always
        expose:
          - "1025"
        ports:
          - "1080:1080"
        networks:
          - penpot
""")


def _get_config():
    """从环境变量/默认值构建配置。"""
    return {
        "penpot_dir": os.environ.get(
            "PENPOT_INSTALL_DIR",
            os.path.join(os.path.expanduser("~"), "penpot-docker"),
        ),
        "penpot_port": int(os.environ.get("PENPOT_PORT", DEFAULT_PENPOT_PORT)),
        "mcp_port": int(os.environ.get("PENPOT_MCP_SERVER_PORT", DEFAULT_MCP_PORT)),
        "plugin_port": int(os.environ.get("PENPOT_MCP_PLUGIN_PORT", DEFAULT_PLUGIN_PORT)),
        "penpot_flags": os.environ.get(
            "PENPOT_FLAGS", "enable-login-with-password"
        ),
    }


# ============================================================================
# Docker Compose 管理
# ============================================================================


def _docker_compose_cmd() -> list:
    """返回可用的 docker compose 命令前缀。"""
    # 优先 docker compose (V2 plugin)
    result = subprocess.run(
        ["docker", "compose", "version"],
        capture_output=True, text=True, timeout=10,
    )
    if result.returncode == 0:
        return ["docker", "compose"]
    # 回退到 docker-compose (standalone)
    if has_command("docker-compose"):
        return ["docker-compose"]
    return []


def _generate_compose_file(config: dict) -> str:
    """生成 docker-compose.yml 路径，如文件不存在则创建。"""
    compose_dir = config["penpot_dir"]
    os.makedirs(compose_dir, exist_ok=True)
    compose_file = os.path.join(compose_dir, "docker-compose.yml")

    if os.path.isfile(compose_file):
        info(f"docker-compose.yml 已存在: {compose_file}")
        return compose_file

    # 生成 PENPOT_SECRET_KEY
    secret_key = secrets.token_hex(32)

    content = DOCKER_COMPOSE_TEMPLATE.format(
        penpot_port=config["penpot_port"],
        penpot_flags=config["penpot_flags"],
        secret_key=secret_key,
    )

    with open(compose_file, "w", encoding="utf-8") as f:
        f.write(content)

    ok(f"已生成 docker-compose.yml: {compose_file}")
    info(f"PENPOT_SECRET_KEY 已自动生成 (存储于 compose 文件中)")
    return compose_file


def _is_penpot_running(config: dict) -> bool:
    """检查 Penpot 前端是否可访问。"""
    return is_port_listening(config["penpot_port"])


def deploy_penpot(config: dict) -> bool:
    """通过 Docker Compose 部署 Penpot。"""
    section("部署 Penpot (Docker Compose)")

    # 检查 Docker
    if not has_command("docker"):
        fail("Docker 未安装。请安装: https://docs.docker.com/get-docker/")
        return False

    docker_ver = get_command_version(["docker", "--version"])
    ok(f"Docker {DIM}({docker_ver}){NC}")

    # 检查 Docker Compose
    dc_cmd = _docker_compose_cmd()
    if not dc_cmd:
        fail("Docker Compose 未安装。请安装 Docker Desktop 或 docker-compose-plugin。")
        return False
    dc_ver = get_command_version(dc_cmd + ["version"])
    ok(f"Docker Compose {DIM}({dc_ver}){NC}")

    # 检查 Docker daemon
    result = subprocess.run(
        ["docker", "info"], capture_output=True, text=True, timeout=15
    )
    if result.returncode != 0:
        fail("Docker daemon 未运行。请启动 Docker Desktop 或 dockerd。")
        return False
    ok("Docker daemon 运行中")

    # 检查端口
    if not check_port_available(config["penpot_port"], "Penpot Frontend"):
        if _is_penpot_running(config):
            info(f"Penpot 已在端口 {config['penpot_port']} 运行，跳过部署")
            return True
        warn(f"端口 {config['penpot_port']} 被其他服务占用，部署可能失败")

    # 生成 compose 文件
    compose_file = _generate_compose_file(config)
    compose_dir = os.path.dirname(compose_file)

    # 拉取镜像
    info("拉取 Docker 镜像 (首次可能需要几分钟)...")
    pull_result = subprocess.run(
        dc_cmd + ["-f", compose_file, "pull"],
        cwd=compose_dir,
        timeout=600,
    )
    if pull_result.returncode != 0:
        warn("镜像拉取可能未完全成功，尝试继续启动...")

    # 启动服务
    info("启动 Penpot 服务...")
    up_result = subprocess.run(
        dc_cmd + ["-f", compose_file, "up", "-d"],
        cwd=compose_dir,
        timeout=120,
    )
    if up_result.returncode != 0:
        fail("Docker Compose 启动失败")
        return False

    # 等待 Penpot 就绪
    info(f"等待 Penpot 就绪 (最多 {HEALTH_TIMEOUT}s)...")
    for i in range(HEALTH_TIMEOUT):
        if _is_penpot_running(config):
            ok(f"Penpot 就绪 {DIM}-> http://localhost:{config['penpot_port']}{NC}")
            return True
        time.sleep(1)
        if (i + 1) % 10 == 0:
            info(f"  已等待 {i + 1}s...")

    warn(f"Penpot 在 {HEALTH_TIMEOUT}s 内未就绪，可能仍在初始化中")
    info(f"请手动检查: docker compose -f {compose_file} logs -f")
    return True  # 不阻断流程，可能只是启动慢


# ============================================================================
# MCP Server 管理 (npx @penpot/mcp@stable)
# ============================================================================


def _read_mcp_pid() -> Optional[int]:
    """读取 MCP Server PID。"""
    if not os.path.isfile(MCP_PID_FILE):
        return None
    try:
        with open(MCP_PID_FILE, "r") as f:
            return int(f.read().strip())
    except (ValueError, OSError):
        return None


def _write_mcp_pid(pid: int):
    """写入 MCP Server PID。"""
    with open(MCP_PID_FILE, "w") as f:
        f.write(str(pid))


def _remove_mcp_pid():
    """移除 PID 文件。"""
    try:
        os.remove(MCP_PID_FILE)
    except OSError:
        pass


def _is_mcp_running(config: dict) -> bool:
    """检查 MCP Server 是否在运行。"""
    return is_port_listening(config["mcp_port"])


def _is_process_alive(pid: int) -> bool:
    """检查进程是否存活。"""
    try:
        if PLATFORM == "windows":
            result = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}"],
                capture_output=True, text=True, timeout=5,
            )
            return str(pid) in result.stdout
        else:
            os.kill(pid, 0)
            return True
    except (OSError, subprocess.TimeoutExpired):
        return False


def start_mcp(config: dict) -> bool:
    """启动 MCP Server (via npx @penpot/mcp@stable)。"""
    section("启动 MCP Server")

    # 检查 Node.js
    if not has_command("node"):
        fail("Node.js 未安装。请安装: https://nodejs.org (v18+)")
        return False
    node_ver = get_command_version(["node", "--version"])
    ok(f"Node.js {DIM}({node_ver}){NC}")

    # 检查 npx
    if not has_command("npx"):
        fail("npx 未找到，请确保 Node.js 安装正确")
        return False

    # 检查端口
    if _is_mcp_running(config):
        ok(f"MCP Server 已在端口 {config['mcp_port']} 运行")
        return True

    if not check_port_available(config["mcp_port"], "MCP Server"):
        return False

    # 构建环境变量
    env = os.environ.copy()
    env["PORT"] = str(config["mcp_port"])
    env["PLUGIN_PORT"] = str(config["plugin_port"])
    env["PENPOT_BASE_URL"] = f"http://localhost:{config['penpot_port']}"

    # 通过 npx 启动 (官方推荐的一行式启动)
    info("通过 npx @penpot/mcp@stable 启动 MCP Server...")
    cmd = ["npx", "@penpot/mcp@stable"]

    log_fh = open(MCP_LOG_FILE, "w", encoding="utf-8")

    if PLATFORM == "windows":
        # Windows: 使用 CREATE_NEW_PROCESS_GROUP 使子进程独立
        proc = subprocess.Popen(
            cmd,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            env=env,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
        )
    else:
        # Unix: 使用 start_new_session 脱离终端
        proc = subprocess.Popen(
            cmd,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            env=env,
            start_new_session=True,
        )

    _write_mcp_pid(proc.pid)
    info(f"MCP Server PID: {proc.pid}, 日志: {MCP_LOG_FILE}")

    # 等待就绪
    for i in range(MCP_HEALTH_TIMEOUT):
        if _is_mcp_running(config):
            ok(f"MCP Server 就绪 {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
            return True
        # 检查进程是否已退出
        if proc.poll() is not None:
            fail(f"MCP Server 进程已退出 (exit={proc.returncode})")
            info(f"查看日志: {MCP_LOG_FILE}")
            _remove_mcp_pid()
            log_fh.close()
            return False
        time.sleep(1)

    warn(f"MCP Server 在 {MCP_HEALTH_TIMEOUT}s 内未就绪")
    info(f"查看日志: {MCP_LOG_FILE}")
    return True  # 不阻断，可能启动较慢


def stop_mcp(config: dict) -> bool:
    """停止 MCP Server。"""
    pid = _read_mcp_pid()

    # 尝试通过 PID 停止
    if pid and _is_process_alive(pid):
        info(f"停止 MCP Server (PID: {pid})...")
        try:
            if PLATFORM == "windows":
                subprocess.run(
                    ["taskkill", "/F", "/PID", str(pid)],
                    capture_output=True, timeout=10,
                )
            else:
                os.kill(pid, signal.SIGTERM)
                # 等待进程退出
                for _ in range(10):
                    if not _is_process_alive(pid):
                        break
                    time.sleep(0.5)
                else:
                    os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
        _remove_mcp_pid()
        ok("MCP Server 已停止")
        return True

    # PID 无效但端口仍在监听
    if _is_mcp_running(config):
        warn(f"端口 {config['mcp_port']} 仍有服务，但无 PID 记录")
        info("请手动停止占用该端口的进程")
        _remove_mcp_pid()
        return False

    info("MCP Server 未在运行")
    _remove_mcp_pid()
    return True


# ============================================================================
# Claude Code MCP 注册
# ============================================================================


def register_claude_mcp(config: dict):
    """注册 Penpot MCP 到 Claude Code。"""
    section("注册 MCP 到 Claude Code")

    mcp_url = f"http://localhost:{config['mcp_port']}/mcp"

    if not has_command("claude"):
        info("Claude Code CLI 未检测到，请手动注册:")
        print(f"\n    {BOLD}claude mcp add penpot -t http {mcp_url}{NC}\n")
        return

    # 检查是否已注册
    result = run_cmd(["claude", "mcp", "list"], timeout=10)
    if result.returncode == 0 and "penpot" in result.stdout.lower():
        ok("Claude Code 已注册 penpot MCP")
        return

    # 注册
    info("注册 Penpot MCP Server...")
    result = run_cmd(["claude", "mcp", "add", "penpot", "-t", "http", mcp_url], timeout=10)
    if result.returncode == 0 or "Added" in (result.stdout or "") or "already" in (result.stdout or ""):
        ok("已注册到 Claude Code")
    else:
        warn(f"自动注册失败 (exit={result.returncode})")
        info(f"请手动执行: claude mcp add penpot -t http {mcp_url}")


# ============================================================================
# 子命令实现
# ============================================================================


def cmd_deploy(config: dict):
    """完整部署: Penpot + MCP。"""
    print(f"\n{CYAN}{BOLD}  Penpot 完整部署 (Docker + MCP){NC}")
    print(f"  {'=' * 44}")
    print(f"  {DIM}Penpot: Docker Compose -> localhost:{config['penpot_port']}{NC}")
    print(f"  {DIM}MCP:    npx @penpot/mcp@stable -> localhost:{config['mcp_port']}{NC}")
    print()

    # Step 1: 部署 Penpot
    if not deploy_penpot(config):
        fail("Penpot 部署失败")
        return 1

    # Step 2: 启动 MCP
    if not start_mcp(config):
        warn("MCP Server 启动异常，但 Penpot 本体已部署")

    # Step 3: 注册到 Claude Code
    register_claude_mcp(config)

    # 完成摘要
    _print_summary(config)
    return 0


def cmd_mcp_only(config: dict):
    """仅启动 MCP Server。"""
    print(f"\n{CYAN}{BOLD}  Penpot MCP Server 部署{NC}")
    print(f"  {'=' * 44}\n")

    # 检查 Penpot 是否在运行
    if not _is_penpot_running(config):
        warn(f"Penpot 未在端口 {config['penpot_port']} 运行")
        info("MCP Server 需要连接到 Penpot 实例才能工作")
        info(f"请先运行: python {__file__} deploy")

    if not start_mcp(config):
        return 1

    register_claude_mcp(config)
    _print_summary(config, penpot_deployed=False)
    return 0


def cmd_start(config: dict):
    """启动已部署的服务。"""
    print(f"\n{CYAN}{BOLD}  启动 Penpot 服务{NC}\n")

    # 启动 Docker Compose
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd:
            section("启动 Penpot (Docker)")
            result = subprocess.run(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"],
                timeout=120,
            )
            if result.returncode == 0:
                ok("Penpot Docker 服务已启动")
            else:
                fail("Penpot Docker 启动失败")
    else:
        info("未找到 Penpot Docker 部署，跳过")

    # 启动 MCP
    start_mcp(config)
    return 0


def cmd_stop(config: dict):
    """停止所有服务。"""
    print(f"\n{CYAN}{BOLD}  停止 Penpot 服务{NC}\n")

    # 停止 MCP
    section("停止 MCP Server")
    stop_mcp(config)

    # 停止 Docker Compose
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd:
            section("停止 Penpot (Docker)")
            result = subprocess.run(
                dc_cmd + ["-f", compose_file, "down"],
                cwd=config["penpot_dir"],
                timeout=120,
            )
            if result.returncode == 0:
                ok("Penpot Docker 服务已停止")
            else:
                fail("Penpot Docker 停止失败")

    return 0


def cmd_status(config: dict):
    """显示服务状态。"""
    print(f"\n{CYAN}{BOLD}  Penpot 服务状态{NC}\n")

    # Penpot
    if _is_penpot_running(config):
        ok(f"Penpot Frontend  {DIM}-> http://localhost:{config['penpot_port']}{NC}")
    else:
        fail(f"Penpot Frontend  (端口 {config['penpot_port']} 未监听)")

    # Docker Compose 详情
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd:
            result = run_cmd(
                dc_cmd + ["-f", compose_file, "ps", "--format", "json"],
                cwd=config["penpot_dir"],
                timeout=10,
            )
            if result.returncode == 0 and result.stdout.strip():
                info("Docker 容器状态:")
                # docker compose ps --format json 可能输出多行 JSON
                for line in result.stdout.strip().splitlines():
                    try:
                        svc = json.loads(line)
                        name = svc.get("Name", svc.get("name", "?"))
                        state = svc.get("State", svc.get("state", "?"))
                        status_str = svc.get("Status", svc.get("status", ""))
                        marker = f"{GREEN}OK{NC}" if state == "running" else f"{RED}{state}{NC}"
                        print(f"    [{marker}] {name} {DIM}{status_str}{NC}")
                    except json.JSONDecodeError:
                        pass

    # MCP Server
    if _is_mcp_running(config):
        ok(f"MCP Server       {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
    else:
        fail(f"MCP Server       (端口 {config['mcp_port']} 未监听)")

    pid = _read_mcp_pid()
    if pid:
        alive = _is_process_alive(pid)
        if alive:
            info(f"MCP PID: {pid} (存活)")
        else:
            warn(f"MCP PID: {pid} (已失效，清理 PID 文件)")
            _remove_mcp_pid()

    # Plugin Server
    if is_port_listening(config["plugin_port"]):
        ok(f"Plugin Server    {DIM}-> http://localhost:{config['plugin_port']}{NC}")
    else:
        info(f"Plugin Server    (端口 {config['plugin_port']} 未监听)")

    print()
    return 0


def cmd_ensure(config: dict):
    """快速模式: 已运行则退出，否则启动。"""
    # MCP 已运行
    if _is_mcp_running(config):
        print(f"Penpot MCP already running on port {config['mcp_port']}")
        return 0

    # Penpot 和 MCP 都未运行，尝试启动
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd and not _is_penpot_running(config):
            subprocess.run(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"],
                capture_output=True,
                timeout=120,
            )
            # 等待 Penpot
            for _ in range(30):
                if _is_penpot_running(config):
                    break
                time.sleep(1)

    # 启动 MCP
    if start_mcp(config):
        return 0

    print(f"Penpot MCP not installed. Run: python {__file__} deploy", file=sys.stderr)
    return 1


# ============================================================================
# 输出辅助
# ============================================================================


def _print_summary(config: dict, penpot_deployed: bool = True):
    """打印部署完成摘要。"""
    print(f"\n  {GREEN}{BOLD}{'=' * 52}{NC}")
    print(f"  {GREEN}{BOLD}  部署完成!{NC}")
    print(f"  {GREEN}{BOLD}{'=' * 52}{NC}\n")

    print(f"  {BOLD}服务端点:{NC}")
    if penpot_deployed:
        print(f"    Penpot Frontend:    {CYAN}http://localhost:{config['penpot_port']}{NC}")
    print(f"    MCP Server (HTTP):  {CYAN}http://localhost:{config['mcp_port']}/mcp{NC}")
    print(f"    MCP Server (SSE):   {CYAN}http://localhost:{config['mcp_port']}/sse{NC}")
    print(f"    Plugin Server:      {CYAN}http://localhost:{config['plugin_port']}{NC}")

    if penpot_deployed:
        print(f"\n  {BOLD}Penpot 初始设置:{NC}")
        print(f"    1. 浏览器打开 {CYAN}http://localhost:{config['penpot_port']}{NC}")
        print(f"    2. 注册本地账号 (邮件发送到 mailcatcher: {CYAN}http://localhost:1080{NC})")
        print(f"    3. 创建项目和设计文件")

    print(f"\n  {BOLD}MCP Plugin 设置:{NC}")
    print(f"    1. 在 Penpot 中打开 Plugins 菜单")
    print(f"    2. 加载插件: {CYAN}http://localhost:{config['plugin_port']}/manifest.json{NC}")
    print(f"    3. 在插件 UI 中点击 {BOLD}\"Connect to MCP server\"{NC}")

    print(f"\n  {BOLD}CataForge 集成:{NC}")
    print(f"    {YELLOW}WARN{NC} 请将 CLAUDE.md 中 {BOLD}设计工具{NC} 改为 {BOLD}penpot{NC}")

    print(f"\n  {BOLD}常用命令:{NC}")
    script = os.path.relpath(__file__, find_project_root())
    print(f"    状态:  {DIM}python {script} status{NC}")
    print(f"    启动:  {DIM}python {script} start{NC}")
    print(f"    停止:  {DIM}python {script} stop{NC}")
    print(f"    日志:  {DIM}cat {MCP_LOG_FILE}{NC}")
    print()


# ============================================================================
# CLI 入口
# ============================================================================


def main():
    ensure_utf8_stdio()

    # 加载 .env
    load_dotenv(override=True)

    parser = argparse.ArgumentParser(
        description="CataForge Penpot 完整部署工具",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            子命令:
              deploy     完整部署: Penpot (Docker) + MCP Server (npx)
              mcp-only   仅启动 MCP Server
              start      启动已部署的服务
              stop       停止所有服务
              status     查看服务状态

            快速模式:
              --ensure   检测已运行则退出，否则启动
        """),
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=["deploy", "mcp-only", "start", "stop", "status"],
        help="子命令",
    )
    parser.add_argument(
        "--ensure",
        action="store_true",
        help="快速模式: 已运行则退出，否则启动",
    )

    args = parser.parse_args()
    config = _get_config()

    if args.ensure:
        sys.exit(cmd_ensure(config))

    if not args.command:
        parser.print_help()
        sys.exit(0)

    handlers = {
        "deploy": cmd_deploy,
        "mcp-only": cmd_mcp_only,
        "start": cmd_start,
        "stop": cmd_stop,
        "status": cmd_status,
    }

    sys.exit(handlers[args.command](config))


if __name__ == "__main__":
    main()
