"""cataforge doctor — environment diagnostics entry.

The actual check implementations live in :mod:`cataforge.cli.doctor`.
This module wires them into the ``doctor`` Click command and exits non-zero
when any migration_check / structural check fails, so CI can treat it as a
gate.
"""

from __future__ import annotations

import shutil
import sys

import click

from cataforge.cli.main import cli

from .doctor._helpers import check_dir, check_file, check_import
from .doctor.deploy_integrity import check_deploy_integrity
from .doctor.event_log import check_event_log_bypass_writes, check_event_log_schema
from .doctor.hook_health import check_hook_script_importability, report_hook_errors
from .doctor.hygiene import check_claude_md_hygiene
from .doctor.kg_ingestion import check_kg_ingestion_completeness
from .doctor.migration import check_runtime_api_version, run_migration_checks
from .doctor.protocol_refs import (
    _DEPRECATED_REFS,
    check_deprecated_references,
    check_protocol_script_references,
)
from .doctor.provenance import report_deployment_provenance
from .doctor.skill_health import check_builtin_skill_reachability, check_docs_validate

__all__ = ["doctor_command", "_DEPRECATED_REFS"]

# Declarative tail of the doctor run: each entry is (header, check, gating).
# ``check(cfg)`` runs after its header is printed; when ``gating`` is True its
# return value (a failure count) is added to the exit-code tally. Informational
# reporters (provenance, hook log) return nothing and never gate. Adding a
# diagnostic is a one-line append here rather than another echo+accumulate pair.
_DOCTOR_SECTIONS = [
    # runtime_api_version contract — drift between scaffold-shipped value and
    # on-disk value means framework.json was authored against a different
    # runtime API revision than the package can serve.
    ("runtime_api_version contract:", check_runtime_api_version, True),
    # Framework migration checks — defined in framework.json, verified here so
    # scaffold/repo drift surfaces automatically instead of only at upgrade time.
    ("Framework migration checks:", run_migration_checks, True),
    # Protocol script references — markdown/YAML in .cataforge/ invoke
    # ``python .cataforge/scripts/...``; a missing script fails silently at
    # runtime, so a static scan catches the rot at diagnostic time.
    ("Protocol script references:", check_protocol_script_references, True),
    ("Deprecated protocol references:", check_deprecated_references, True),
    ("Docs validation:", check_docs_validate, True),
    # KG ingestion completeness — hard ERROR gate ensuring the KG is the single
    # source of truth for active doc_types (ERROR when an FS entity_id is
    # missing from the graph; skipped when no store exists).
    ("KG ingestion completeness:", check_kg_ingestion_completeness, True),
    ("Hook script importability:", check_hook_script_importability, True),
    ("Built-in skill reachability:", check_builtin_skill_reachability, True),
    ("EVENT-LOG schema sample:", check_event_log_schema, True),
    ("EVENT-LOG bypass guard:", check_event_log_bypass_writes, True),
    ("CLAUDE.md hygiene:", check_claude_md_hygiene, True),
    # Deployment provenance — informational: shows which platform dirs the last
    # deploy would have written so users see what is CataForge-managed.
    ("Deployment provenance:", report_deployment_provenance, False),
    # Deploy integrity — the hard gate: turns dangling links / missing owned
    # dirs into FAILs so post-deploy regressions can't slip past doctor.
    ("Deploy integrity:", check_deploy_integrity, True),
    # Recent hook execution failures — informational; surfaces silent
    # observer-hook crashes logged by hook_main().
    ("Hook execution log:", report_hook_errors, False),
]


@cli.command("doctor")
@click.pass_context
def doctor_command(ctx: click.Context) -> None:
    """Run environment diagnostics and report issues.

    Exits with a non-zero status when any migration_check fails, so CI can
    treat doctor as a gate.
    """
    from cataforge.cli.helpers import get_config_manager
    from cataforge.cli.ui import ui

    ui.header("CataForge Doctor", subtitle="Environment + scaffold integrity gate")

    cfg = get_config_manager()

    # Python
    click.echo(f"\nPython: {sys.version}")
    click.echo(f"  Executable: {sys.executable}")

    # Framework — these are the source assets every CataForge project must
    # carry. Missing any of them is a setup failure, not a notice.
    click.echo(f"\nProject root: {cfg.paths.root}")
    failed_count = 0
    failed_count += check_file(
        "framework.json", cfg.paths.framework_json, required=True
    )
    # PROJECT-STATE.md is auto-generated by deploy and not always present
    # before the first deploy, so it stays informational.
    check_file("PROJECT-STATE.md", cfg.paths.project_state_md)
    failed_count += check_dir(
        ".cataforge/agents", cfg.paths.agents_dir, required=True
    )
    failed_count += check_dir(
        ".cataforge/skills", cfg.paths.skills_dir, required=True
    )
    failed_count += check_dir(
        ".cataforge/rules", cfg.paths.rules_dir, required=True
    )
    failed_count += check_dir(
        ".cataforge/hooks", cfg.paths.hooks_dir, required=True
    )
    failed_count += check_file(
        "hooks.yaml", cfg.paths.hooks_spec, required=True
    )
    failed_count += check_dir(
        ".cataforge/platforms", cfg.paths.platforms_dir, required=True
    )

    # Config
    click.echo(f"\nFramework version: {cfg.version}")
    click.echo(f"Runtime platform: {cfg.runtime_platform}")

    # Dependencies — these two are load-bearing for the CLI itself; if
    # either is missing the user can't run any cataforge command, so
    # gate doctor's exit code on them. ``check_import(..., required=True)``
    # mirrors the same pattern check_file / check_dir already use.
    click.echo("\nDependencies:")
    failed_count += check_import("yaml", "PyYAML", required=True)
    failed_count += check_import("click", "click", required=True)

    # External tools — diagnostic patterns for missing tools live in
    # cataforge.cli.diagnostics so the same diagnosis/fix copy is shown by
    # other commands that probe these binaries (penpot doctor, hook tests).
    from cataforge.cli.diagnostics import DOCTOR_PATTERNS
    from cataforge.cli.ui import ui as _ui

    click.echo("\nExternal tools:")
    missing_tools_blob: list[str] = []
    for tool in ("ruff", "npx", "docker", "git"):
        path = shutil.which(tool)
        status = f"found ({path})" if path else "not found"
        click.echo(f"  {tool}: {status}")
        if path is None:
            missing_tools_blob.append(f"{tool}: not found")
    if missing_tools_blob:
        _ui.diagnose("\n".join(missing_tools_blob), DOCTOR_PATTERNS)

    # Platform profiles
    click.echo("\nPlatform profiles:")
    for pid in ("claude-code", "cursor", "codex", "opencode"):
        path = cfg.paths.platform_profile(pid)
        status = "OK" if path.is_file() else "MISSING"
        click.echo(f"  {pid}: {status}")

    for header, check, gating in _DOCTOR_SECTIONS:
        click.echo(f"\n{header}")
        result = check(cfg)
        if gating:
            failed_count += result

    click.echo("\nDiagnostics complete.")
    _print_summary(failed_count)

    if failed_count:
        ctx.exit(1)


def _print_summary(failed_count: int) -> None:
    """Final one-line verdict so users do not have to scan every section.

    Kept intentionally minimal: a count of failures is the load-bearing
    datum. Section-level pass counts would require threading through more
    state than the value adds — sections already print their own running
    tallies (e.g. ``7/7 built-in skills``).
    """
    from cataforge.cli.guidance import print_next_steps
    from cataforge.cli.ui import NextStep, ui

    if failed_count == 0:
        ui.ok("Summary: all checks passed.")
        print_next_steps("doctor-pass")
        return
    ui.fail(
        f"Summary: {failed_count} failed — see FAIL lines above."
    )
    # Tailored next-steps when doctor fails — the right follow-up depends on
    # the symptom class. We give a triage list rather than a single command.
    ui.next_steps([
        NextStep("cataforge deploy", "if FAIL was in `Deploy integrity`"),
        NextStep("cataforge upgrade apply", "if FAIL was in `Framework migration checks`"),
        NextStep("cataforge doctor", "rerun to confirm after fixing"),
    ])
