"""cataforge doctor — environment diagnostics entry.

The actual check implementations live in :mod:`cataforge.cli.doctor`.
This module wires them into the ``doctor`` Click command and exits non-zero
when any migration_check / structural check fails, so CI can treat it as a
gate.
"""

from __future__ import annotations

import shutil
import sys

import click

from cataforge.cli.main import cli

from .doctor._helpers import check_dir, check_file, check_import
from .doctor.deploy_integrity import check_deploy_integrity
from .doctor.event_log import check_event_log_bypass_writes, check_event_log_schema
from .doctor.hook_health import check_hook_script_importability, report_hook_errors
from .doctor.hygiene import check_claude_md_hygiene
from .doctor.kg_ingestion import check_kg_ingestion_completeness
from .doctor.migration import check_runtime_api_version, run_migration_checks
from .doctor.protocol_refs import (
    _DEPRECATED_REFS,
    check_deprecated_references,
    check_protocol_script_references,
)
from .doctor.provenance import report_deployment_provenance
from .doctor.skill_health import check_builtin_skill_reachability, check_docs_validate

__all__ = ["doctor_command", "_DEPRECATED_REFS"]


@cli.command("doctor")
@click.pass_context
def doctor_command(ctx: click.Context) -> None:
    """Run environment diagnostics and report issues.

    Exits with a non-zero status when any migration_check fails, so CI can
    treat doctor as a gate.
    """
    from cataforge.cli.helpers import get_config_manager
    from cataforge.cli.ui import ui

    ui.header("CataForge Doctor", subtitle="Environment + scaffold integrity gate")

    cfg = get_config_manager()

    # Python
    click.echo(f"\nPython: {sys.version}")
    click.echo(f"  Executable: {sys.executable}")

    # Framework — these are the source assets every CataForge project must
    # carry. Missing any of them is a setup failure, not a notice.
    click.echo(f"\nProject root: {cfg.paths.root}")
    failed_count = 0
    failed_count += check_file(
        "framework.json", cfg.paths.framework_json, required=True
    )
    # PROJECT-STATE.md is auto-generated by deploy and not always present
    # before the first deploy, so it stays informational.
    check_file("PROJECT-STATE.md", cfg.paths.project_state_md)
    failed_count += check_dir(
        ".cataforge/agents", cfg.paths.agents_dir, required=True
    )
    failed_count += check_dir(
        ".cataforge/skills", cfg.paths.skills_dir, required=True
    )
    failed_count += check_dir(
        ".cataforge/rules", cfg.paths.rules_dir, required=True
    )
    failed_count += check_dir(
        ".cataforge/hooks", cfg.paths.hooks_dir, required=True
    )
    failed_count += check_file(
        "hooks.yaml", cfg.paths.hooks_spec, required=True
    )
    failed_count += check_dir(
        ".cataforge/platforms", cfg.paths.platforms_dir, required=True
    )

    # Config
    click.echo(f"\nFramework version: {cfg.version}")
    click.echo(f"Runtime platform: {cfg.runtime_platform}")

    # Dependencies — these two are load-bearing for the CLI itself; if
    # either is missing the user can't run any cataforge command, so
    # gate doctor's exit code on them. ``check_import(..., required=True)``
    # mirrors the same pattern check_file / check_dir already use.
    click.echo("\nDependencies:")
    failed_count += check_import("yaml", "PyYAML", required=True)
    failed_count += check_import("click", "click", required=True)

    # External tools — diagnostic patterns for missing tools live in
    # cataforge.cli.diagnostics so the same diagnosis/fix copy is shown by
    # other commands that probe these binaries (penpot doctor, hook tests).
    from cataforge.cli.diagnostics import DOCTOR_PATTERNS
    from cataforge.cli.ui import ui as _ui

    click.echo("\nExternal tools:")
    missing_tools_blob: list[str] = []
    for tool in ("ruff", "npx", "docker", "git"):
        path = shutil.which(tool)
        status = f"found ({path})" if path else "not found"
        click.echo(f"  {tool}: {status}")
        if path is None:
            missing_tools_blob.append(f"{tool}: not found")
    if missing_tools_blob:
        _ui.diagnose("\n".join(missing_tools_blob), DOCTOR_PATTERNS)

    # Platform profiles
    click.echo("\nPlatform profiles:")
    for pid in ("claude-code", "cursor", "codex", "opencode"):
        path = cfg.paths.platform_profile(pid)
        status = "OK" if path.is_file() else "MISSING"
        click.echo(f"  {pid}: {status}")

    # runtime_api_version contract — drift between scaffold-shipped value
    # and on-disk value means the user's framework.json was authored
    # against a different runtime API revision than the package can serve.
    click.echo("\nruntime_api_version contract:")
    failed_count += check_runtime_api_version(cfg)

    # Framework migration checks — defined in framework.json, verified here so
    # scaffold/repo drift surfaces automatically instead of only at upgrade time.
    click.echo("\nFramework migration checks:")
    failed_count += run_migration_checks(cfg)

    # Protocol script references — markdown/YAML files inside .cataforge/
    # routinely invoke ``python .cataforge/scripts/...`` commands. If one of
    # those scripts is missing, every call site silently fails at runtime,
    # with no signal until someone reads the hook error log. Static scan
    # catches the rot at diagnostic time.
    click.echo("\nProtocol script references:")
    failed_count += check_protocol_script_references(cfg)

    click.echo("\nDeprecated protocol references:")
    failed_count += check_deprecated_references(cfg)

    click.echo("\nDocs validation:")
    failed_count += check_docs_validate(cfg)

    # KG ingestion completeness — hard ERROR gate ensuring the KG is the
    # single source of truth for active doc_types. Skipped when no store
    # has been initialized; ERROR when any FS-discovered entity_id is
    # missing from the graph. Per Task 7 §7.1 sub-PR 5.
    click.echo("\nKG ingestion completeness:")
    failed_count += check_kg_ingestion_completeness(cfg)

    click.echo("\nHook script importability:")
    failed_count += check_hook_script_importability(cfg)

    click.echo("\nBuilt-in skill reachability:")
    failed_count += check_builtin_skill_reachability(cfg)

    click.echo("\nEVENT-LOG schema sample:")
    failed_count += check_event_log_schema(cfg)

    click.echo("\nEVENT-LOG bypass guard:")
    failed_count += check_event_log_bypass_writes(cfg)

    click.echo("\nCLAUDE.md hygiene:")
    failed_count += check_claude_md_hygiene(cfg)

    # Deployment provenance — shows which platform-specific directories would
    # have been written by the last successful deploy. Lets users see at a
    # glance which ``.claude/`` / ``.cursor/`` / etc. are CataForge-managed
    # vs user/IDE-native.
    click.echo("\nDeployment provenance:")
    report_deployment_provenance(cfg)

    # Deploy integrity — the hard gate. provenance.py prints ``[present]`` /
    # ``[absent]`` but never failed the run; this check turns dangling links
    # and missing owned dirs into FAILs that contribute to the exit code,
    # so post-deploy regressions cannot slip past doctor unnoticed.
    click.echo("\nDeploy integrity:")
    failed_count += check_deploy_integrity(cfg)

    # Recent hook execution failures — logged by hook_main() so silent
    # observer-hook crashes don't stay invisible.
    click.echo("\nHook execution log:")
    report_hook_errors(cfg)

    click.echo("\nDiagnostics complete.")
    _print_summary(failed_count)

    if failed_count:
        ctx.exit(1)


def _print_summary(failed_count: int) -> None:
    """Final one-line verdict so users do not have to scan every section.

    Kept intentionally minimal: a count of failures is the load-bearing
    datum. Section-level pass counts would require threading through more
    state than the value adds — sections already print their own running
    tallies (e.g. ``7/7 built-in skills``).
    """
    from cataforge.cli.guidance import print_next_steps
    from cataforge.cli.ui import NextStep, ui

    if failed_count == 0:
        ui.ok("Summary: all checks passed.")
        print_next_steps("doctor-pass")
        return
    ui.fail(
        f"Summary: {failed_count} failed — see FAIL lines above."
    )
    # Tailored next-steps when doctor fails — the right follow-up depends on
    # the symptom class. We give a triage list rather than a single command.
    ui.next_steps([
        NextStep("cataforge deploy", "if FAIL was in `Deploy integrity`"),
        NextStep("cataforge upgrade apply", "if FAIL was in `Framework migration checks`"),
        NextStep("cataforge doctor", "rerun to confirm after fixing"),
    ])
