"""OpenCode hooks materialise as a generated TypeScript plugin (C4).

Before this change OpenCode had every hook tagged ``degraded`` with no
actual degradation implementation — deploying to OpenCode silently dropped
every hook on the floor.  Now the adapter emits one plugin that spawns the
same Python scripts every other platform uses.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from cataforge.platform.opencode import OpenCodeAdapter, _render_opencode_plugin


@pytest.fixture()
def opencode_adapter() -> OpenCodeAdapter:
    profile = {
        "platform_id": "opencode",
        "tool_map": {"shell_exec": "bash", "file_edit": "edit"},
        "hooks": {
            "config_format": "plugin",
            "event_map": {
                "PreToolUse": "tool.execute.before",
                "PostToolUse": "tool.execute.after",
            },
            "degradation": {"guard_dangerous": "native", "lint_format": "native"},
        },
    }
    return OpenCodeAdapter(profile)


def test_render_plugin_shape() -> None:
    """Output is valid-looking TS with a HOOKS descriptor and dispatcher."""
    ts = _render_opencode_plugin(
        {
            "tool.execute.before": [
                {"script": "guard_dangerous", "matcher_capability": "shell_exec", "type": "block"}
            ],
            "tool.execute.after": [
                {"script": "lint_format", "matcher_capability": "file_edit", "type": "observe"}
            ],
        }
    )

    assert "Auto-generated by `cataforge deploy`" in ts
    assert "const HOOKS = {" in ts
    assert '"tool.execute.before"' in ts
    assert '"script": "guard_dangerous"' in ts
    assert '"type": "block"' in ts
    assert "spawn(" in ts
    # Block hooks propagate refusal via throw (OpenCode plugin contract)
    assert "throw new Error" in ts


def test_emit_plugin_hooks_writes_file(
    opencode_adapter: OpenCodeAdapter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    # Stub load_hooks_spec so the generator doesn't reach into the repo.
    import cataforge.hook.bridge as bridge

    monkeypatch.setattr(
        bridge,
        "load_hooks_spec",
        lambda _p=None: {
            "schema_version": 2,
            "hooks": {
                "PreToolUse": [
                    {
                        "script": "guard_dangerous",
                        "matcher_capability": "shell_exec",
                        "type": "block",
                    }
                ],
                "PostToolUse": [
                    {
                        "script": "lint_format",
                        "matcher_capability": "file_edit",
                        "type": "observe",
                    }
                ],
            },
        },
    )

    actions = opencode_adapter.emit_plugin_hooks(tmp_path, dry_run=False)

    plugin_path = tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts"
    assert plugin_path.is_file()
    assert any("cataforge-hooks.ts" in a for a in actions)

    body = plugin_path.read_text(encoding="utf-8")
    assert "guard_dangerous" in body
    assert "lint_format" in body


def test_emit_plugin_hooks_dry_run_does_not_write(
    opencode_adapter: OpenCodeAdapter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import cataforge.hook.bridge as bridge

    monkeypatch.setattr(
        bridge,
        "load_hooks_spec",
        lambda _p=None: {
            "hooks": {
                "PreToolUse": [
                    {
                        "script": "guard_dangerous",
                        "matcher_capability": "shell_exec",
                        "type": "block",
                    }
                ]
            }
        },
    )

    actions = opencode_adapter.emit_plugin_hooks(tmp_path, dry_run=True)
    assert any("would write" in a for a in actions)
    assert not (tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts").exists()


def test_apply_degradation_emits_plugin_on_opencode(
    opencode_adapter: OpenCodeAdapter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The public entry point used by deploy() routes through the plugin."""
    import cataforge.hook.bridge as bridge

    monkeypatch.setattr(
        bridge,
        "load_hooks_spec",
        lambda _p=None: {
            "hooks": {
                "PreToolUse": [
                    {
                        "script": "guard_dangerous",
                        "matcher_capability": "shell_exec",
                        "type": "block",
                    }
                ]
            },
            "degradation_templates": {},
        },
    )

    actions = bridge.apply_degradation(opencode_adapter, tmp_path, dry_run=False)
    assert any("opencode plugin" in a for a in actions)
    assert (tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts").is_file()
