"""OpenCode hooks materialise as a generated TypeScript plugin (C4).

Before this change OpenCode had every hook tagged ``degraded`` with no
actual degradation implementation — deploying to OpenCode silently dropped
every hook on the floor.  Now the adapter emits one plugin that spawns the
same Python scripts every other platform uses.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from cataforge.adapter.platform.opencode import OpenCodeAdapter, _render_opencode_plugin
from cataforge.adapter.platform.profile_schema import PlatformProfile

_NODE = shutil.which("node")


@pytest.fixture()
def opencode_adapter() -> OpenCodeAdapter:
    profile = PlatformProfile.model_validate(
        {
            "platform_id": "opencode",
            "tool_map": {"shell_exec": "bash", "file_edit": "edit"},
            "hooks": {
                "config_format": "plugin",
                "event_map": {
                    "PreToolUse": "tool.execute.before",
                    "PostToolUse": "tool.execute.after",
                },
                "degradation": {"guard_dangerous": "native", "lint_format": "native"},
            },
        }
    )
    return OpenCodeAdapter(profile)


def test_render_plugin_shape() -> None:
    """Output is valid-looking TS with a HOOKS descriptor and dispatcher."""
    ts = _render_opencode_plugin(
        {
            "tool.execute.before": [
                {"script": "guard_dangerous", "matcher_capability": "shell_exec", "type": "block"}
            ],
            "tool.execute.after": [
                {"script": "lint_format", "matcher_capability": "file_edit", "type": "observe"}
            ],
        }
    )

    assert "Auto-generated by `cataforge deploy`" in ts
    assert "const HOOKS = {" in ts
    assert '"tool.execute.before"' in ts
    assert '"script": "guard_dangerous"' in ts
    assert '"type": "block"' in ts
    assert "spawn(" in ts
    # Block hooks propagate refusal via throw (OpenCode plugin contract)
    assert "throw new Error" in ts


def test_render_plugin_spawns_deploying_interpreter() -> None:
    """The spawned interpreter is the deploy-time ``sys.executable`` (as a
    JSON-escaped forward-slash literal), never a bare ``python`` lookup."""
    import json as _json
    import sys
    from pathlib import Path

    ts = _render_opencode_plugin(
        {
            "tool.execute.before": [
                {"script": "guard_dangerous", "matcher_capability": "shell_exec", "type": "block"}
            ],
        }
    )

    assert _json.dumps(Path(sys.executable).as_posix()) in ts
    assert "spawn(\n      'python'," not in ts and "spawn('python'" not in ts


def test_block_hook_fails_closed_on_spawn_error() -> None:
    """A block hook must refuse when its Python guard cannot run cleanly.

    Guards the regression where ``child.on('error', () => resolve(0))`` plus a
    ``code === 2``-only throw let a missing python/cataforge silently allow
    guard_dangerous.
    """
    ts = _render_opencode_plugin(
        {
            "tool.execute.before": [
                {"script": "guard_dangerous", "matcher_capability": "shell_exec", "type": "block"}
            ],
        }
    )

    # The fail-open construct must be gone.
    assert "resolve(0)" not in ts
    # Spawn error / null exit resolve to the fail-closed sentinel.
    assert "const failCode = isBlock ? 2 : 0;" in ts
    assert "child.on('error', () => resolve(failCode));" in ts
    assert "resolve(code ?? failCode)" in ts
    # Block dispatch refuses on any non-clean exit, not only the explicit 2.
    assert "h.type === 'block' && code !== 0" in ts


def test_descriptor_carries_matcher_agent_id() -> None:
    """The TS descriptor carries matcher_agent_id so the dispatcher can
    pre-filter on the dispatched agent before paying the python startup."""
    ts = _render_opencode_plugin(
        {
            "tool.execute.after": [
                {
                    "script": "detect_review_flag",
                    "matcher_capability": "agent_dispatch",
                    "type": "observe",
                    "matcher_agent_id": ["reviewer"],
                }
            ],
        }
    )
    assert '"matcher_agent_id"' in ts
    assert '"reviewer"' in ts
    # Pre-filter helper present and wired into the dispatch loop.
    assert "function agentMatches" in ts
    assert "if (!agentMatches(h.matcher_agent_id, payload)) continue;" in ts
    # Mirror of Python's candidate extraction order.
    assert "ti.subagent_type ?? ti.agent_type ?? ti.agent ?? payload.agent" in ts


@pytest.mark.skipif(_NODE is None, reason="node not available")
def test_real_plugin_passes_node_check(tmp_path: Path) -> None:
    """Deploy the real OpenCode plugin and assert node can parse it — the
    artifact behaviour-level check for the TS surface."""
    from cataforge.adapter.platform.registry import clear_cache, get_adapter
    from cataforge.runtime.hook.bridge import load_hooks_spec

    clear_cache()
    adapter = get_adapter("opencode")
    adapter.emit_plugin_hooks(tmp_path, dry_run=False, hooks_spec=load_hooks_spec())
    plugin = tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts"
    assert plugin.is_file()

    assert _NODE is not None
    result = subprocess.run(
        [_NODE, "--check", str(plugin)], capture_output=True, text=True, timeout=60
    )
    assert result.returncode == 0, result.stderr

    body = plugin.read_text(encoding="utf-8")
    # detect_review_flag's matcher_agent_id allowlist reaches the real artifact.
    assert "matcher_agent_id" in body
    assert "reviewer" in body
    assert "function agentMatches" in body


def test_emit_plugin_hooks_writes_file(
    opencode_adapter: OpenCodeAdapter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    # Stub load_hooks_spec so the generator doesn't reach into the repo.
    import cataforge.runtime.hook.bridge as bridge

    monkeypatch.setattr(
        bridge,
        "load_hooks_spec",
        lambda _p=None: {
            "schema_version": 2,
            "hooks": {
                "PreToolUse": [
                    {
                        "script": "guard_dangerous",
                        "matcher_capability": "shell_exec",
                        "type": "block",
                    }
                ],
                "PostToolUse": [
                    {
                        "script": "lint_format",
                        "matcher_capability": "file_edit",
                        "type": "observe",
                    }
                ],
            },
        },
    )

    actions = opencode_adapter.emit_plugin_hooks(
        tmp_path, dry_run=False, hooks_spec=bridge.load_hooks_spec()
    )

    plugin_path = tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts"
    assert plugin_path.is_file()
    assert any("cataforge-hooks.ts" in a for a in actions)

    body = plugin_path.read_text(encoding="utf-8")
    assert "guard_dangerous" in body
    assert "lint_format" in body


def test_emit_plugin_hooks_dry_run_does_not_write(
    opencode_adapter: OpenCodeAdapter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import cataforge.runtime.hook.bridge as bridge

    monkeypatch.setattr(
        bridge,
        "load_hooks_spec",
        lambda _p=None: {
            "hooks": {
                "PreToolUse": [
                    {
                        "script": "guard_dangerous",
                        "matcher_capability": "shell_exec",
                        "type": "block",
                    }
                ]
            }
        },
    )

    actions = opencode_adapter.emit_plugin_hooks(
        tmp_path, dry_run=True, hooks_spec=bridge.load_hooks_spec()
    )
    assert any("would write" in a for a in actions)
    assert not (tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts").exists()


def test_apply_degradation_emits_plugin_on_opencode(
    opencode_adapter: OpenCodeAdapter,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The public entry point used by deploy() routes through the plugin."""
    import cataforge.runtime.hook.bridge as bridge

    monkeypatch.setattr(
        bridge,
        "load_hooks_spec",
        lambda _p=None: {
            "hooks": {
                "PreToolUse": [
                    {
                        "script": "guard_dangerous",
                        "matcher_capability": "shell_exec",
                        "type": "block",
                    }
                ]
            },
            "degradation_templates": {},
        },
    )

    actions = bridge.apply_degradation(opencode_adapter, tmp_path, dry_run=False)
    assert any("opencode plugin" in a for a in actions)
    assert (tmp_path / ".opencode" / "plugins" / "cataforge-hooks.ts").is_file()
