#!/usr/bin/env python3
"""setup_penpot.py — CataForge Penpot 完整部署工具 (Python)

Plan A 架构: Docker Compose 部署 Penpot 本体 + npx 启动 MCP Server。

子命令:
  deploy       完整部署: Penpot (Docker) + MCP Server (npx)
  mcp-only     仅启动 MCP Server (假设 Penpot 已运行)
  start        启动已部署的服务 (Penpot + MCP)
  stop         停止所有服务
  status       查看服务状态
  --ensure     快速模式: 检测已运行则退出，否则启动

用法:
  python .claude/integrations/penpot/setup_penpot.py deploy      # 完整部署
  python .claude/integrations/penpot/setup_penpot.py mcp-only    # 仅 MCP
  python .claude/integrations/penpot/setup_penpot.py start       # 启动服务
  python .claude/integrations/penpot/setup_penpot.py stop        # 停止服务
  python .claude/integrations/penpot/setup_penpot.py status      # 查看状态
  python .claude/integrations/penpot/setup_penpot.py --ensure    # 快速检查/启动

环境变量 (可选覆盖，可写入 .env):
  PENPOT_INSTALL_DIR          Penpot Docker Compose 目录 (默认: ~/penpot-docker)
  PENPOT_PORT                 Penpot 前端端口 (默认: 9001)
  PENPOT_MCP_SERVER_PORT      MCP Server 端口 (默认: 4401)
  PENPOT_MCP_PLUGIN_PORT      Plugin Server 端口 (默认: 4400)
  PENPOT_FLAGS                Penpot feature flags (默认: 本地开发推荐配置)
"""

import argparse
import json
import locale
import os
import secrets
import signal
import socket
import subprocess
import sys
import textwrap
import time
import urllib.error
import urllib.request
from typing import Optional
from urllib.parse import urlparse

# 确保 .claude/scripts/lib/_common 可导入
_here = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.abspath(os.path.join(_here, os.pardir, os.pardir, os.pardir))
sys.path.insert(0, os.path.join(_project_root, ".claude", "scripts", "lib"))
from _common import (
    BOLD,
    CYAN,
    DIM,
    GREEN,
    NC,
    RED,
    YELLOW,
    check_port_available,
    detect_platform,
    ensure_docker_proxy,
    ensure_utf8_stdio,
    fail,
    find_available_port,
    find_project_root,
    get_command_version,
    has_command,
    info,
    is_port_listening,
    load_dotenv,
    ok,
    run_cmd,
    section,
    warn,
)

# ============================================================================
# 配置
# ============================================================================

PLATFORM = detect_platform()

# 默认端口
DEFAULT_PENPOT_PORT = 9001
DEFAULT_MCP_PORT = 4401
DEFAULT_PLUGIN_PORT = 4400

# 健康检查超时 (秒)
HEALTH_TIMEOUT = 60
MCP_HEALTH_TIMEOUT = 120  # 首次启动需下载 pnpm 依赖，30s 不够

# 镜像拉取重试次数
PULL_MAX_RETRIES = 3

# Docker 镜像源列表 (按优先级排序，空字符串表示官方 Docker Hub)
# 代理可用时 Docker Hub 直连最可靠，国内镜像作为回退
# 参考: https://github.com/dongyubin/DockerHub
DOCKER_REGISTRY_MIRRORS = [
    "",  # Docker Hub 官方 (代理可用时优先)
    "docker.xuanyuan.me",  # 轩辕镜像免费版
    "docker.m.daocloud.io",  # DaoCloud
    "mirror.ccs.tencentyun.com",  # 腾讯云 (云服务器内效果最佳)
]

# PID 文件 (跨平台临时目录)
import tempfile as _tempfile

_TMPDIR = _tempfile.gettempdir()
MCP_PID_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.pid")
MCP_LOG_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.log")

# Docker Compose 模板 (基于 Penpot 官方配置)
# 参考: https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml
DOCKER_COMPOSE_TEMPLATE = textwrap.dedent("""\
    ## Penpot Docker Compose — auto-generated by CataForge setup_penpot.py
    ## Based on: https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml
    ##
    ## 6 services: frontend, backend, exporter, postgres, valkey, mailcatch
    ## Ports: {penpot_port}:8080 (frontend)

    networks:
      penpot:

    volumes:
      penpot_postgres_v15:
      penpot_assets:

    services:
      penpot-frontend:
        image: penpotapp/frontend:latest
        restart: always
        ports:
          - "{penpot_port}:8080"
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          - penpot-backend
          - penpot-exporter
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600

      penpot-backend:
        image: penpotapp/backend:latest
        restart: always
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          penpot-postgres:
            condition: service_healthy
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://localhost:{penpot_port}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
          - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
          - PENPOT_DATABASE_USERNAME=penpot
          - PENPOT_DATABASE_PASSWORD=penpot
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
          - PENPOT_OBJECTS_STORAGE_BACKEND=fs
          - PENPOT_OBJECTS_STORAGE_FS_DIRECTORY=/opt/data/assets
          - PENPOT_TELEMETRY_ENABLED=false
          - PENPOT_SMTP_DEFAULT_FROM=no-reply@penpot.local
          - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@penpot.local
          - PENPOT_SMTP_HOST=penpot-mailcatch
          - PENPOT_SMTP_PORT=1025
          - PENPOT_SMTP_TLS=false
          - PENPOT_SMTP_SSL=false

      penpot-exporter:
        image: penpotapp/exporter:latest
        restart: always
        depends_on:
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
          - PENPOT_REDIS_URI=redis://penpot-valkey/0

      penpot-postgres:
        image: postgres:15
        restart: always
        stop_signal: SIGINT
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U penpot"]
          interval: 2s
          timeout: 10s
          retries: 5
          start_period: 2s
        volumes:
          - penpot_postgres_v15:/var/lib/postgresql/data
        networks:
          - penpot
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=penpot
          - POSTGRES_USER=penpot
          - POSTGRES_PASSWORD=penpot

      penpot-valkey:
        image: valkey/valkey:8.1
        restart: always
        healthcheck:
          test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
          interval: 1s
          timeout: 3s
          retries: 5
          start_period: 3s
        networks:
          - penpot
        environment:
          - VALKEY_EXTRA_FLAGS=--maxmemory 128mb --maxmemory-policy volatile-lfu

      penpot-mailcatch:
        image: sj26/mailcatcher:latest
        restart: always
        expose:
          - "1025"
        ports:
          - "1080:1080"
        networks:
          - penpot
""")


def _get_config():
    """从环境变量/默认值构建配置。"""
    return {
        "penpot_dir": os.environ.get(
            "PENPOT_INSTALL_DIR",
            os.path.join(os.path.expanduser("~"), "penpot-docker"),
        ),
        "penpot_port": int(os.environ.get("PENPOT_PORT", DEFAULT_PENPOT_PORT)),
        "mcp_port": int(os.environ.get("PENPOT_MCP_SERVER_PORT", DEFAULT_MCP_PORT)),
        "plugin_port": int(
            os.environ.get("PENPOT_MCP_PLUGIN_PORT", DEFAULT_PLUGIN_PORT)
        ),
        "penpot_flags": os.environ.get(
            "PENPOT_FLAGS",
            "enable-login-with-password disable-email-verification "
            "enable-smtp enable-prepl-server disable-secure-session-cookies",
        ),
    }


# ============================================================================
# Docker Compose 管理
# ============================================================================


def _docker_compose_cmd() -> list:
    """返回可用的 docker compose 命令前缀。"""
    # 优先 docker compose (V2 plugin)
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            return ["docker", "compose"]
    except (FileNotFoundError, OSError):
        pass
    # 回退到 docker-compose (standalone)
    if has_command("docker-compose"):
        return ["docker-compose"]
    return []


def _find_docker_desktop_exe() -> Optional[str]:
    """查找 Windows 上 Docker Desktop 的可执行文件路径。"""
    candidates = [
        r"C:\Program Files\Docker\Docker\Docker Desktop.exe",
        os.path.join(
            os.environ.get("ProgramFiles", r"C:\Program Files"),
            "Docker",
            "Docker",
            "Docker Desktop.exe",
        ),
        os.path.join(
            os.environ.get("LOCALAPPDATA", ""), "Docker", "Docker Desktop.exe"
        ),
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


def _start_docker_desktop() -> bool:
    """尝试启动 Docker Desktop (Windows)，最多等待 90s 直到 daemon 就绪。"""
    exe = _find_docker_desktop_exe()
    if not exe:
        return False

    info(f"启动 Docker Desktop: {exe}")
    subprocess.Popen(
        [exe],
        creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP,
        close_fds=True,
    )

    info("等待 Docker daemon 就绪 (最多 90s)...")
    for i in range(90):
        try:
            result = subprocess.run(
                ["docker", "info"], capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                ok(f"Docker daemon 已就绪 (等待了 {i + 1}s)")
                return True
        except subprocess.TimeoutExpired:
            pass  # daemon 仍在启动中，继续等待
        time.sleep(1)
        if (i + 1) % 15 == 0:
            info(f"  已等待 {i + 1}s...")

    return False


def _install_docker_windows() -> bool:
    """通过 winget 安装 Docker Desktop (需管理员权限)。"""
    if not has_command("winget"):
        fail("winget 未找到，无法自动安装 Docker Desktop")
        info("请手动下载安装: https://docs.docker.com/desktop/install/windows-install/")
        return False

    info("通过 winget 安装 Docker Desktop (需要管理员权限)...")
    result = subprocess.run(
        [
            "winget",
            "install",
            "--id",
            "Docker.DockerDesktop",
            "--accept-package-agreements",
            "--accept-source-agreements",
        ],
        timeout=600,
    )
    if result.returncode != 0:
        fail(f"winget 安装失败 (exit={result.returncode})")
        info("请手动下载安装: https://docs.docker.com/desktop/install/windows-install/")
        return False

    ok("Docker Desktop 安装完成")
    return True


def _ensure_docker_running() -> bool:
    """确保 Docker daemon 在运行，必要时自动启动或安装 Docker Desktop。"""
    # 先检查 daemon 是否已运行
    try:
        result = subprocess.run(
            ["docker", "info"], capture_output=True, text=True, timeout=15
        )
        if result.returncode == 0:
            ok("Docker daemon 运行中")
            return True
    except subprocess.TimeoutExpired:
        pass  # daemon 未响应，继续尝试启动

    if PLATFORM == "windows":
        # 尝试启动已安装的 Docker Desktop
        if _find_docker_desktop_exe():
            warn("Docker daemon 未运行，尝试自动启动 Docker Desktop...")
            if _start_docker_desktop():
                return True
            fail("Docker Desktop 启动超时，请手动启动后重试")
            return False
        else:
            # Docker 未安装，尝试通过 winget 安装
            warn("Docker Desktop 未安装，尝试通过 winget 自动安装...")
            if not _install_docker_windows():
                return False
            # 安装后启动
            if _find_docker_desktop_exe() and _start_docker_desktop():
                return True
            fail("安装后仍无法启动 Docker daemon，请手动启动 Docker Desktop")
            return False

    elif PLATFORM == "macos":
        warn("Docker daemon 未运行，尝试启动 Docker Desktop...")
        subprocess.Popen(["open", "-a", "Docker"])
        info("等待 Docker daemon 就绪 (最多 90s)...")
        for i in range(90):
            result = subprocess.run(
                ["docker", "info"], capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                ok(f"Docker daemon 已就绪 (等待了 {i + 1}s)")
                return True
            time.sleep(1)
            if (i + 1) % 15 == 0:
                info(f"  已等待 {i + 1}s...")
        fail("Docker Desktop 启动超时，请手动启动后重试")
        return False

    else:
        # Linux: 尝试通过 systemctl 或 service 启动
        warn("Docker daemon 未运行，尝试通过 systemctl 启动...")
        started = False
        if has_command("systemctl"):
            r = subprocess.run(
                ["sudo", "systemctl", "start", "docker"],
                capture_output=True,
                timeout=30,
            )
            started = r.returncode == 0
        if not started and has_command("service"):
            r = subprocess.run(
                ["sudo", "service", "docker", "start"],
                capture_output=True,
                timeout=30,
            )
            started = r.returncode == 0
        if not started:
            fail("无法自动启动 Docker daemon。请运行: sudo systemctl start docker")
            return False
        # 验证
        for _ in range(15):
            result = subprocess.run(
                ["docker", "info"], capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                ok("Docker daemon 已就绪")
                return True
            time.sleep(1)
        fail("Docker daemon 启动后未就绪，请检查: sudo systemctl status docker")
        return False


def _extract_secret_key(compose_file: str) -> Optional[str]:
    """从已有 compose 文件中提取 PENPOT_SECRET_KEY。"""
    try:
        with open(compose_file, "r", encoding="utf-8") as f:
            for line in f:
                if "PENPOT_SECRET_KEY=" in line:
                    val = line.split("=", 1)[1].strip()
                    # 去除 YAML 中可能的引号包裹
                    if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
                        val = val[1:-1]
                    return val
    except OSError:
        pass
    return None


def _generate_compose_file(config: dict, force: bool = False) -> str:
    """生成 docker-compose.yml，端口变更时自动重新生成。

    Args:
        config: 部署配置 (含端口号)。
        force: 为 True 时强制重新生成 (端口变更场景)。
    """
    compose_dir = config["penpot_dir"]
    os.makedirs(compose_dir, exist_ok=True)
    compose_file = os.path.join(compose_dir, "docker-compose.yml")

    if os.path.isfile(compose_file) and not force:
        info(f"docker-compose.yml 已存在: {compose_file}")
        return compose_file

    # 复用已有 secret key，避免重新生成导致 backend 认证失败
    secret_key = (
        _extract_secret_key(compose_file) if os.path.isfile(compose_file) else None
    ) or secrets.token_hex(32)

    content = DOCKER_COMPOSE_TEMPLATE.format(
        penpot_port=config["penpot_port"],
        penpot_flags=config["penpot_flags"],
        secret_key=secret_key,
    )

    with open(compose_file, "w", encoding="utf-8") as f:
        f.write(content)

    label = "已重新生成" if force else "已生成"
    ok(f"{label} docker-compose.yml: {compose_file}")
    if not force:
        info("PENPOT_SECRET_KEY 已自动生成 (存储于 compose 文件中)")
    return compose_file


def _is_penpot_container_running() -> bool:
    """通过 Docker 检查 Penpot 容器是否在运行。"""
    try:
        r = subprocess.run(
            ["docker", "ps", "--filter", "name=penpot", "--format", "{{.Names}}"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return bool(r.stdout.strip())
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def _is_penpot_running(config: dict) -> bool:
    """检查 Penpot 是否在运行 (Docker 容器 + 端口双重验证)。"""
    return _is_penpot_container_running() and is_port_listening(config["penpot_port"])


# ============================================================================
# 统一依赖预检
# ============================================================================


def preflight_check(scope: str = "all") -> bool:
    """统一检查并安装所有外部依赖。

    Args:
        scope: "all" = Docker + Node.js 全量检查 (deploy/start)
               "mcp" = 仅 Node.js 相关 (mcp-only)

    Returns:
        True 全部依赖就绪，False 存在不可恢复缺失。
    """
    section("依赖预检")
    passed = True

    # --- Docker 系列 (仅 scope=all) ---
    if scope == "all":
        if not has_command("docker"):
            fail("Docker 未安装。请安装: https://docs.docker.com/get-docker/")
            passed = False
        else:
            docker_ver = get_command_version(["docker", "--version"])
            ok(f"Docker {DIM}({docker_ver}){NC}")

        dc_cmd = _docker_compose_cmd()
        if not dc_cmd:
            fail(
                "Docker Compose 未安装。请安装 Docker Desktop 或 docker-compose-plugin。"
            )
            passed = False
        else:
            dc_ver = get_command_version(dc_cmd + ["version"])
            ok(f"Docker Compose {DIM}({dc_ver}){NC}")

    # --- Node.js 系列 ---
    if not has_command("node"):
        fail("Node.js 未安装。请安装: https://nodejs.org (v18+)")
        passed = False
    else:
        node_ver = get_command_version(["node", "--version"])
        ok(f"Node.js {DIM}({node_ver}){NC}")

    if not has_command("npx"):
        fail("npx 未找到，请确保 Node.js 安装正确")
        passed = False
    else:
        ok("npx")

    # --- corepack (@penpot/mcp 的 pnpm 通过 corepack 调用) ---
    if not has_command("corepack"):
        info("安装 corepack (pnpm 包管理器依赖)...")
        # Windows 上 npm 是 .cmd 脚本，需通过 shell 执行
        r = subprocess.run(
            "npm install -g corepack",
            shell=True,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if r.returncode != 0:
            fail("corepack 安装失败，请手动执行: npm install -g corepack")
            passed = False
        else:
            ok("corepack 已安装")
    else:
        # Windows 上 corepack 是 .cmd 脚本，get_command_version 不走 shell 会失败
        try:
            cp_ver = subprocess.run(
                "corepack --version",
                shell=True,
                capture_output=True,
                text=True,
                timeout=10,
            ).stdout.strip()
        except (subprocess.TimeoutExpired, OSError):
            cp_ver = ""
        ok(f"corepack {DIM}({cp_ver}){NC}")

    # 确保 corepack 已启用 (使 pnpm 可通过 corepack 调用)
    # Windows 上 corepack 是 .cmd 脚本，需通过 shell 执行
    if has_command("corepack"):
        subprocess.run(
            "corepack enable",
            shell=True,
            capture_output=True,
            timeout=30,
        )

    if not passed:
        fail("依赖预检未通过，请先安装缺失的依赖")
    return passed


def _rewrite_image(image: str, mirror: str) -> str:
    """将镜像名重写为指定 mirror 前缀。

    Docker Hub 镜像格式:
      - 官方镜像: postgres:15 -> mirror/library/postgres:15
      - 用户镜像: penpotapp/frontend:latest -> mirror/penpotapp/frontend:latest
    mirror 为空字符串时返回原始镜像名 (使用 Docker Hub 官方)。
    """
    if not mirror:
        return image
    # 分离 tag
    if ":" in image:
        name, tag = image.rsplit(":", 1)
    else:
        name, tag = image, "latest"
    # 官方镜像 (无 / 的) 需加 library/ 前缀
    if "/" not in name:
        name = f"library/{name}"
    return f"{mirror}/{name}:{tag}"


def _ensure_docker_proxy():
    """检测环境代理并配置到 Docker daemon — 委托给 _common.ensure_docker_proxy。"""
    ensure_docker_proxy()


def _is_mirror_reachable(mirror: str, timeout: float = 3.0) -> bool:
    """Quick TCP connectivity check for a Docker registry mirror.

    Avoids wasting minutes on pull retries against unreachable mirrors.
    """
    if not mirror:
        return True  # Docker Hub — reachability depends on daemon proxy, skip check
    try:
        parsed = urlparse(f"https://{mirror}")
        host = parsed.hostname or mirror
        port = parsed.port or 443
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            s.connect((host, port))
            return True
    except (ConnectionRefusedError, TimeoutError, OSError):
        return False


def _pull_image_with_mirrors(image: str) -> bool:
    """尝试从多个镜像源拉取单个镜像，每个源最多重试 PULL_MAX_RETRIES 次。

    对每个 mirror 先做 TCP 连通性预检（3s），不可达则直接跳过，
    避免在已失效的镜像源上浪费拉取超时。
    成功拉取后，若使用的是 mirror，会 tag 回原始镜像名以保证 compose 可用。
    """
    for mirror in DOCKER_REGISTRY_MIRRORS:
        source_label = mirror if mirror else "Docker Hub"
        # Quick reachability check for third-party mirrors
        if mirror and not _is_mirror_reachable(mirror):
            info(f"  [{source_label}] 不可达，跳过")
            continue
        rewritten = _rewrite_image(image, mirror)
        for attempt in range(1, PULL_MAX_RETRIES + 1):
            info(
                f"  [{source_label}] 拉取 {rewritten} (第 {attempt}/{PULL_MAX_RETRIES} 次)..."
            )
            try:
                result = subprocess.run(
                    ["docker", "pull", rewritten],
                    capture_output=True,
                    text=True,
                    timeout=300,
                )
                if result.returncode == 0:
                    ok(f"  {image} <- {source_label}")
                    # mirror 拉取成功后 tag 回原始名称
                    if mirror:
                        subprocess.run(
                            ["docker", "tag", rewritten, image],
                            capture_output=True,
                            timeout=30,
                        )
                    return True
            except subprocess.TimeoutExpired:
                warn(f"  [{source_label}] 拉取超时")
            except OSError as e:
                warn(f"  [{source_label}] 拉取异常: {e}")
        # 当前 mirror 全部重试失败，尝试下一个
        if mirror:
            info(f"  {source_label} 拉取失败，切换下一个镜像源...")
    return False


def _pull_all_images(compose_file: str) -> bool:
    """从 compose 文件中提取所有镜像并逐个拉取 (带镜像源重试)。

    返回 True 表示全部成功，False 表示存在失败 (但不阻断流程)。
    """
    # 从 compose 文件解析 image 字段
    images = []
    try:
        with open(compose_file, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith("image:"):
                    img = stripped.split(":", 1)[1].strip().strip('"').strip("'")
                    # 去除行尾 YAML 注释
                    if "  #" in img:
                        img = img[: img.index("  #")].rstrip()
                    if img:
                        images.append(img)
    except OSError:
        warn(f"无法读取 compose 文件: {compose_file}")
        return False

    if not images:
        warn("未在 compose 文件中找到任何镜像定义")
        return False

    info(f"共需拉取 {len(images)} 个镜像")
    all_ok = True
    for image in images:
        if not _pull_image_with_mirrors(image):
            warn(f"  {image} 所有镜像源均失败")
            all_ok = False
    return all_ok


def deploy_penpot(config: dict) -> bool:
    """通过 Docker Compose 部署 Penpot。依赖已由 preflight_check 确认。"""
    section("部署 Penpot (Docker Compose)")

    # 确保 Docker daemon 运行（自动启动或安装）
    if not _ensure_docker_running():
        return False

    # 检查 Penpot 是否已在运行 (Docker 容器 + 端口双重验证)
    if _is_penpot_running(config):
        ok("Penpot 已在运行，跳过部署")
        return True

    # 端口可用性检测，冲突时自动切换
    orig_port = config["penpot_port"]
    config["penpot_port"] = find_available_port(orig_port, "Penpot Frontend")
    port_changed = config["penpot_port"] != orig_port

    # 获取 Docker Compose 命令 (已由 preflight_check 确认可用)
    dc_cmd = _docker_compose_cmd()

    # 生成 compose 文件 (端口变更时强制重新生成)
    compose_file = _generate_compose_file(config, force=port_changed)
    compose_dir = os.path.dirname(compose_file)

    # 配置 Docker daemon 代理 (使 docker pull 能走代理)
    _ensure_docker_proxy()

    # 拉取镜像 (多镜像源 + 重试)
    info("拉取 Docker 镜像 (首次可能需要几分钟)...")
    if not _pull_all_images(compose_file):
        warn("部分镜像拉取失败，尝试继续启动...")

    # 启动服务
    info("启动 Penpot 服务...")
    up_result = subprocess.run(
        dc_cmd + ["-f", compose_file, "up", "-d"],
        cwd=compose_dir,
        timeout=120,
    )
    if up_result.returncode != 0:
        fail("Docker Compose 启动失败")
        return False

    # 等待 Penpot 就绪
    info(f"等待 Penpot 就绪 (最多 {HEALTH_TIMEOUT}s)...")
    for i in range(HEALTH_TIMEOUT):
        if _is_penpot_running(config):
            ok(f"Penpot 就绪 {DIM}-> http://localhost:{config['penpot_port']}{NC}")
            return True
        time.sleep(1)
        if (i + 1) % 10 == 0:
            info(f"  已等待 {i + 1}s...")

    warn(f"Penpot 在 {HEALTH_TIMEOUT}s 内未就绪，可能仍在初始化中")
    info(f"请手动检查: docker compose -f {compose_file} logs -f")
    return True  # 不阻断流程，可能只是启动慢


# ============================================================================
# MCP Server 管理 (npx @penpot/mcp@latest)
# ============================================================================


def _read_mcp_pid() -> Optional[int]:
    """读取 MCP Server PID。"""
    if not os.path.isfile(MCP_PID_FILE):
        return None
    try:
        with open(MCP_PID_FILE, "r") as f:
            return int(f.read().strip())
    except (ValueError, OSError):
        return None


def _write_mcp_pid(pid: int):
    """写入 MCP Server PID。"""
    with open(MCP_PID_FILE, "w") as f:
        f.write(str(pid))


def _remove_mcp_pid():
    """移除 PID 文件。"""
    try:
        os.remove(MCP_PID_FILE)
    except OSError:
        pass


def _is_mcp_running(config: dict) -> bool:
    """检查 MCP Server 是否在运行 (HTTP 探测)。"""
    try:
        req = urllib.request.Request(
            f"http://localhost:{config['mcp_port']}/mcp",
            method="GET",
        )
        urllib.request.urlopen(req, timeout=2)
        return True
    except urllib.error.HTTPError:
        # 任何 HTTP 响应 (如 405/406) 说明服务已启动
        return True
    except (urllib.error.URLError, OSError, TimeoutError):
        return False


def _is_process_alive(pid: int) -> bool:
    """检查进程是否存活。"""
    try:
        if PLATFORM == "windows":
            result = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            return str(pid) in result.stdout
        else:
            os.kill(pid, 0)
            return True
    except (OSError, subprocess.TimeoutExpired):
        return False


def _print_mcp_log_tail(max_lines: int = 10):
    """读取并打印 MCP 日志末尾，自动检测编码。"""
    if not os.path.isfile(MCP_LOG_FILE):
        return
    try:
        with open(MCP_LOG_FILE, "rb") as f:
            raw = f.read()
        if not raw:
            return
        # 尝试 UTF-8，退回系统编码 (Windows 常为 GBK)，最终用 replace
        for enc in ("utf-8", locale.getpreferredencoding(False), "latin-1"):
            try:
                text = raw.decode(enc)
                break
            except (UnicodeDecodeError, LookupError):
                continue
        else:
            text = raw.decode("latin-1")
        lines = text.strip().splitlines()[-max_lines:]
        info(f"日志末尾 ({MCP_LOG_FILE}):")
        for line in lines:
            print(f"    {line}")
    except OSError:
        info(f"查看日志: {MCP_LOG_FILE}")


def start_mcp(config: dict) -> bool:
    """启动 MCP Server (via npx @penpot/mcp@latest)。依赖已由 preflight_check 确认。"""
    section("启动 MCP Server")

    # 检查 MCP 是否已运行
    if _is_mcp_running(config):
        ok(f"MCP Server 已在端口 {config['mcp_port']} 运行")
        return True

    # 端口可用性检测，冲突时自动切换
    config["mcp_port"] = find_available_port(config["mcp_port"], "MCP Server")
    config["plugin_port"] = find_available_port(config["plugin_port"], "Plugin Server")

    # 构建环境变量
    env = os.environ.copy()
    env["PORT"] = str(config["mcp_port"])
    env["PLUGIN_PORT"] = str(config["plugin_port"])
    env["PENPOT_BASE_URL"] = f"http://localhost:{config['penpot_port']}"

    # 通过 npx 启动 (官方推荐的一行式启动)
    info("通过 npx @penpot/mcp@latest 启动 MCP Server...")
    cmd = ["npx", "--yes", "@penpot/mcp@latest"]

    # 二进制模式写入日志: subprocess 在 Windows 上输出系统编码 (GBK/CP936)，
    # 用 "wb" 保留原始字节，读取时再自动检测编码，避免乱码
    log_fh = open(MCP_LOG_FILE, "wb")

    if PLATFORM == "windows":
        # Windows: npx 是 .cmd 脚本，必须通过 shell=True 执行
        proc = subprocess.Popen(
            cmd,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            env=env,
            shell=True,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
        )
    else:
        # Unix: 使用 start_new_session 脱离终端
        proc = subprocess.Popen(
            cmd,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            env=env,
            start_new_session=True,
        )

    _write_mcp_pid(proc.pid)
    info(f"MCP Server PID: {proc.pid}, 日志: {MCP_LOG_FILE}")

    # 子进程已接管 log_fh 文件描述符，父进程应关闭自己的句柄
    # 避免 Windows 上文件锁定导致后续日志读取失败
    log_fh.close()

    # 等待就绪 (首次启动需下载 pnpm 依赖，可能耗时较长)
    info(f"等待 MCP Server 就绪 (最多 {MCP_HEALTH_TIMEOUT}s)...")
    for i in range(MCP_HEALTH_TIMEOUT):
        if _is_mcp_running(config):
            ok(f"MCP Server 就绪 {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
            return True
        # 检查进程是否已退出
        if proc.poll() is not None:
            fail(f"MCP Server 进程已退出 (exit={proc.returncode})")
            _print_mcp_log_tail()
            _remove_mcp_pid()
            return False
        time.sleep(1)
        if (i + 1) % 15 == 0:
            info(f"  已等待 {i + 1}s...")

    warn(f"MCP Server 在 {MCP_HEALTH_TIMEOUT}s 内未就绪")
    _print_mcp_log_tail()
    return True  # 不阻断，可能启动较慢


def stop_mcp(config: dict) -> bool:
    """停止 MCP Server。"""
    pid = _read_mcp_pid()

    # 尝试通过 PID 停止
    if pid and _is_process_alive(pid):
        info(f"停止 MCP Server (PID: {pid})...")
        try:
            if PLATFORM == "windows":
                # /T 终止进程树（含 shell=True 产生的 cmd.exe 子进程）
                subprocess.run(
                    ["taskkill", "/F", "/T", "/PID", str(pid)],
                    capture_output=True,
                    timeout=10,
                )
            else:
                os.kill(pid, signal.SIGTERM)
                # 等待进程退出
                for _ in range(10):
                    if not _is_process_alive(pid):
                        break
                    time.sleep(0.5)
                else:
                    os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
        _remove_mcp_pid()
        ok("MCP Server 已停止")
        return True

    # PID 无效但端口仍在监听
    if _is_mcp_running(config):
        warn(f"端口 {config['mcp_port']} 仍有服务，但无 PID 记录")
        info("请手动停止占用该端口的进程")
        _remove_mcp_pid()
        return False

    info("MCP Server 未在运行")
    _remove_mcp_pid()
    return True


# ============================================================================
# Claude Code MCP 注册
# ============================================================================


def register_claude_mcp(config: dict):
    """注册 Penpot MCP 到 Claude Code。"""
    section("注册 MCP 到 Claude Code")

    mcp_url = f"http://localhost:{config['mcp_port']}/mcp"

    if not has_command("claude"):
        info("Claude Code CLI 未检测到，请手动注册:")
        print(f"\n    {BOLD}claude mcp add penpot -t http {mcp_url}{NC}\n")
        return

    # 检查是否已注册
    result = run_cmd(["claude", "mcp", "list"], timeout=10)
    if result.returncode == 0 and result.stdout and "penpot" in result.stdout.lower():
        ok("Claude Code 已注册 penpot MCP")
        return

    # 注册
    info("注册 Penpot MCP Server...")
    result = run_cmd(
        ["claude", "mcp", "add", "penpot", "-t", "http", mcp_url], timeout=10
    )
    if (
        result.returncode == 0
        or "Added" in (result.stdout or "")
        or "already" in (result.stdout or "")
    ):
        ok("已注册到 Claude Code")
    else:
        warn(f"自动注册失败 (exit={result.returncode})")
        info(f"请手动执行: claude mcp add penpot -t http {mcp_url}")


# ============================================================================
# 子命令实现
# ============================================================================


def cmd_deploy(config: dict):
    """完整部署: Penpot + MCP。"""
    print(f"\n{CYAN}{BOLD}  Penpot 完整部署 (Docker + MCP){NC}")
    print(f"  {'=' * 44}")
    print(f"  {DIM}Penpot: Docker Compose -> localhost:{config['penpot_port']}{NC}")
    print(
        f"  {DIM}MCP:    npx @penpot/mcp@latest -> localhost:{config['mcp_port']}{NC}"
    )
    print()

    # Step 0: 统一依赖预检
    if not preflight_check("all"):
        return 1

    # Step 1: 部署 Penpot
    if not deploy_penpot(config):
        fail("Penpot 部署失败")
        return 1

    # Step 2: 启动 MCP
    if not start_mcp(config):
        warn("MCP Server 启动异常，但 Penpot 本体已部署")

    # Step 3: 注册到 Claude Code
    register_claude_mcp(config)

    # 完成摘要
    _print_summary(config)
    return 0


def cmd_mcp_only(config: dict):
    """仅启动 MCP Server。"""
    print(f"\n{CYAN}{BOLD}  Penpot MCP Server 部署{NC}")
    print(f"  {'=' * 44}\n")

    # 统一依赖预检 (仅 Node.js 相关)
    if not preflight_check("mcp"):
        return 1

    # 检查 Penpot 是否在运行
    if not _is_penpot_running(config):
        warn(f"Penpot 未在端口 {config['penpot_port']} 运行")
        info("MCP Server 需要连接到 Penpot 实例才能工作")
        info(f"请先运行: python {__file__} deploy")

    if not start_mcp(config):
        return 1

    register_claude_mcp(config)
    _print_summary(config, penpot_deployed=False)
    return 0


def cmd_start(config: dict):
    """启动已部署的服务。"""
    print(f"\n{CYAN}{BOLD}  启动 Penpot 服务{NC}\n")

    # 统一依赖预检
    if not preflight_check("all"):
        return 1

    # 启动 Docker Compose
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd:
            section("启动 Penpot (Docker)")
            if not _ensure_docker_running():
                fail("Docker daemon 未就绪，跳过 Penpot 启动")
            else:
                result = subprocess.run(
                    dc_cmd + ["-f", compose_file, "up", "-d"],
                    cwd=config["penpot_dir"],
                    timeout=120,
                )
                if result.returncode == 0:
                    ok("Penpot Docker 服务已启动")
                else:
                    fail("Penpot Docker 启动失败")
    else:
        info("未找到 Penpot Docker 部署，跳过")

    # 启动 MCP
    start_mcp(config)
    return 0


def cmd_stop(config: dict):
    """停止所有服务。"""
    print(f"\n{CYAN}{BOLD}  停止 Penpot 服务{NC}\n")

    # 停止 MCP
    section("停止 MCP Server")
    stop_mcp(config)

    # 停止 Docker Compose
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd:
            section("停止 Penpot (Docker)")
            result = subprocess.run(
                dc_cmd + ["-f", compose_file, "down"],
                cwd=config["penpot_dir"],
                timeout=120,
            )
            if result.returncode == 0:
                ok("Penpot Docker 服务已停止")
            else:
                fail("Penpot Docker 停止失败")

    return 0


def cmd_status(config: dict):
    """显示服务状态。"""
    print(f"\n{CYAN}{BOLD}  Penpot 服务状态{NC}\n")

    # Penpot
    if _is_penpot_running(config):
        ok(f"Penpot Frontend  {DIM}-> http://localhost:{config['penpot_port']}{NC}")
    else:
        fail(f"Penpot Frontend  (端口 {config['penpot_port']} 未监听)")

    # Docker Compose 详情
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = _docker_compose_cmd()
        if dc_cmd:
            result = run_cmd(
                dc_cmd + ["-f", compose_file, "ps", "--format", "json"],
                cwd=config["penpot_dir"],
                timeout=10,
            )
            if result.returncode == 0 and result.stdout.strip():
                info("Docker 容器状态:")
                # docker compose ps --format json 可能输出多行 JSON
                for line in result.stdout.strip().splitlines():
                    try:
                        svc = json.loads(line)
                        name = svc.get("Name", svc.get("name", "?"))
                        state = svc.get("State", svc.get("state", "?"))
                        status_str = svc.get("Status", svc.get("status", ""))
                        marker = (
                            f"{GREEN}OK{NC}"
                            if state == "running"
                            else f"{RED}{state}{NC}"
                        )
                        print(f"    [{marker}] {name} {DIM}{status_str}{NC}")
                    except json.JSONDecodeError:
                        pass

    # MCP Server
    if _is_mcp_running(config):
        ok(f"MCP Server       {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
    else:
        fail(f"MCP Server       (端口 {config['mcp_port']} 未监听)")

    pid = _read_mcp_pid()
    if pid:
        alive = _is_process_alive(pid)
        if alive:
            info(f"MCP PID: {pid} (存活)")
        else:
            warn(f"MCP PID: {pid} (已失效，清理 PID 文件)")
            _remove_mcp_pid()

    # Plugin Server
    if is_port_listening(config["plugin_port"]):
        ok(f"Plugin Server    {DIM}-> http://localhost:{config['plugin_port']}{NC}")
    else:
        info(f"Plugin Server    (端口 {config['plugin_port']} 未监听)")

    print()
    return 0


def cmd_ensure(config: dict):
    """快速模式: 已运行则退出，否则启动。"""
    # MCP 已运行
    if _is_mcp_running(config):
        print(f"Penpot MCP already running on port {config['mcp_port']}")
        return 0

    # Penpot 和 MCP 都未运行，尝试启动
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        # 确保 Docker daemon 在运行
        if has_command("docker") and not _ensure_docker_running():
            fail("Docker daemon 无法启动，请手动启动 Docker Desktop")
            return 1
        dc_cmd = _docker_compose_cmd()
        if dc_cmd and not _is_penpot_running(config):
            subprocess.run(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"],
                capture_output=True,
                timeout=120,
            )
            # 等待 Penpot
            for _ in range(30):
                if _is_penpot_running(config):
                    break
                time.sleep(1)

    # 启动 MCP
    if start_mcp(config):
        return 0

    print(f"Penpot MCP not installed. Run: python {__file__} deploy", file=sys.stderr)
    return 1


# ============================================================================
# 输出辅助
# ============================================================================


def _print_summary(config: dict, penpot_deployed: bool = True):
    """打印部署完成摘要。"""
    print(f"\n  {GREEN}{BOLD}{'=' * 52}{NC}")
    print(f"  {GREEN}{BOLD}  部署完成!{NC}")
    print(f"  {GREEN}{BOLD}{'=' * 52}{NC}\n")

    print(f"  {BOLD}服务端点:{NC}")
    if penpot_deployed:
        print(
            f"    Penpot Frontend:    {CYAN}http://localhost:{config['penpot_port']}{NC}"
        )
    print(
        f"    MCP Server (HTTP):  {CYAN}http://localhost:{config['mcp_port']}/mcp{NC}"
    )
    print(
        f"    MCP Server (SSE):   {CYAN}http://localhost:{config['mcp_port']}/sse{NC}"
    )
    print(f"    Plugin Server:      {CYAN}http://localhost:{config['plugin_port']}{NC}")

    if penpot_deployed:
        print(f"\n  {BOLD}Penpot 初始设置:{NC}")
        print(f"    1. 浏览器打开 {CYAN}http://localhost:{config['penpot_port']}{NC}")
        print(
            f"    2. 注册本地账号 (邮件发送到 mailcatcher: {CYAN}http://localhost:1080{NC})"
        )
        print("    3. 创建项目和设计文件")

    print(f"\n  {BOLD}MCP Plugin 设置:{NC}")
    print("    1. 在 Penpot 中打开 Plugins 菜单")
    print(
        f"    2. 加载插件: {CYAN}http://localhost:{config['plugin_port']}/manifest.json{NC}"
    )
    print(f'    3. 在插件 UI 中点击 {BOLD}"Connect to MCP server"{NC}')

    print(f"\n  {BOLD}CataForge 集成:{NC}")
    print(
        f"    {YELLOW}WARN{NC} 请将 CLAUDE.md 中 {BOLD}设计工具{NC} 改为 {BOLD}penpot{NC}"
    )

    print(f"\n  {BOLD}常用命令:{NC}")
    script = os.path.relpath(__file__, find_project_root())
    print(f"    状态:  {DIM}python {script} status{NC}")
    print(f"    启动:  {DIM}python {script} start{NC}")
    print(f"    停止:  {DIM}python {script} stop{NC}")
    print(f"    日志:  {DIM}cat {MCP_LOG_FILE}{NC}")
    print()


# ============================================================================
# CLI 入口
# ============================================================================


def main():
    ensure_utf8_stdio()

    # 加载 .env
    load_dotenv(set_env=True)

    parser = argparse.ArgumentParser(
        description="CataForge Penpot 完整部署工具",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            子命令:
              deploy     完整部署: Penpot (Docker) + MCP Server (npx)
              mcp-only   仅启动 MCP Server
              start      启动已部署的服务
              stop       停止所有服务
              status     查看服务状态

            快速模式:
              --ensure   检测已运行则退出，否则启动
        """),
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=["deploy", "mcp-only", "start", "stop", "status"],
        help="子命令",
    )
    parser.add_argument(
        "--ensure",
        action="store_true",
        help="快速模式: 已运行则退出，否则启动",
    )

    args = parser.parse_args()
    config = _get_config()

    if args.ensure:
        sys.exit(cmd_ensure(config))

    if not args.command:
        parser.print_help()
        sys.exit(0)

    handlers = {
        "deploy": cmd_deploy,
        "mcp-only": cmd_mcp_only,
        "start": cmd_start,
        "stop": cmd_stop,
        "status": cmd_status,
    }

    sys.exit(handlers[args.command](config))


if __name__ == "__main__":
    main()
