"""Penpot integration — shared constants and the Docker Compose template."""

from __future__ import annotations

import os
import tempfile
import textwrap

from cataforge.utils.common import detect_platform

PLATFORM = detect_platform()

DEFAULT_PENPOT_PORT = 9001
DEFAULT_MCP_PORT = 4401
DEFAULT_PLUGIN_PORT = 4400

# Single version knob for the self-hosted Docker stack: frontend, backend,
# exporter and the penpot-mcp container all share this tag so the frontend
# image and its MCP sidecar can never drift apart. Override with PENPOT_VERSION.
DEFAULT_PENPOT_VERSION = "2.16"

# npm @penpot/mcp version for the host-side npx MCP used by `remote` / `mcp-only`
# (those modes have no Docker stack). Override with PENPOT_MCP_VERSION.
DEFAULT_MCP_PACKAGE_VERSION = "2.15.0"

# Node major versions @penpot/mcp upstream tests against. Outside this range
# we still let the user proceed (warn only) — pinning hard is too aggressive
# given how often Node majors shift on developer machines.
SUPPORTED_NODE_MAJORS = (20, 22)

HEALTH_TIMEOUT = 60
MCP_HEALTH_TIMEOUT = 120

DOCKER_REGISTRY_MIRRORS = [
    "",
    "docker.xuanyuan.me",
    "docker.m.daocloud.io",
    "mirror.ccs.tencentyun.com",
]

_TMPDIR = tempfile.gettempdir()
MCP_PID_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.pid")
MCP_LOG_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.log")


DOCKER_COMPOSE_TEMPLATE = textwrap.dedent("""\
    ## Penpot Docker Compose — auto-generated by CataForge
    networks:
      penpot:
    volumes:
      penpot_postgres_v15:
      penpot_assets:
    services:
      penpot-frontend:
        image: penpotapp/frontend:{penpot_version}
        restart: always
        ports:
          - "{penpot_port}:8080"
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          - penpot-backend
          - penpot-exporter
          - penpot-mcp
        networks:
          - penpot
        environment:
          # enable-mcp wires frontend nginx /mcp/{{stream,sse,ws}} to the
          # penpot-mcp container (PENPOT_MCP_URI defaults to
          # http://penpot-mcp:4401 and :4402 inside the compose network).
          - PENPOT_FLAGS={penpot_flags} enable-mcp
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
      penpot-mcp:
        image: penpotapp/mcp:{penpot_version}
        restart: always
        networks:
          - penpot
      penpot-backend:
        image: penpotapp/backend:{penpot_version}
        restart: always
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          penpot-postgres:
            condition: service_healthy
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags} enable-mcp
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://localhost:{penpot_port}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
          - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
          - PENPOT_DATABASE_USERNAME=penpot
          - PENPOT_DATABASE_PASSWORD=penpot
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
          - PENPOT_OBJECTS_STORAGE_BACKEND=fs
          - PENPOT_OBJECTS_STORAGE_FS_DIRECTORY=/opt/data/assets
          - PENPOT_TELEMETRY_ENABLED=false
          - PENPOT_SMTP_DEFAULT_FROM=no-reply@penpot.local
          - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@penpot.local
          - PENPOT_SMTP_HOST=penpot-mailcatch
          - PENPOT_SMTP_PORT=1025
          - PENPOT_SMTP_TLS=false
          - PENPOT_SMTP_SSL=false
      penpot-exporter:
        image: penpotapp/exporter:{penpot_version}
        restart: always
        depends_on:
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
      penpot-postgres:
        image: postgres:15
        restart: always
        stop_signal: SIGINT
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U penpot"]
          interval: 2s
          timeout: 10s
          retries: 5
          start_period: 2s
        volumes:
          - penpot_postgres_v15:/var/lib/postgresql/data
        networks:
          - penpot
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=penpot
          - POSTGRES_USER=penpot
          - POSTGRES_PASSWORD=penpot
      penpot-valkey:
        image: valkey/valkey:8.1
        restart: always
        healthcheck:
          test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
          interval: 1s
          timeout: 3s
          retries: 5
          start_period: 3s
        networks:
          - penpot
        environment:
          - VALKEY_EXTRA_FLAGS=--maxmemory 128mb --maxmemory-policy volatile-lfu
      penpot-mailcatch:
        image: sj26/mailcatcher:latest
        restart: always
        expose:
          - "1025"
        ports:
          - "1080:1080"
        networks:
          - penpot
""")
