#!/usr/bin/env python3
"""Generate Pydantic models, SHACL shapes, and rdfs:subClassOf axioms from LinkML schemas.

Reads:
  - src/cataforge/kg/schemas/core.yaml
  - src/cataforge/kg/schemas/governance.yaml

Writes (under src/cataforge/kg/_generated/, gitignored):
  - core_pydantic.py            Pydantic v2 models for the business ontology
  - governance_pydantic.py      Pydantic v2 models for governance sub-ontology
  - core_shapes.ttl             SHACL shapes for business ontology
  - governance_shapes.ttl       SHACL shapes for governance sub-ontology
  - subclass_axioms.ttl         is_a chain materialized as rdfs:subClassOf triples;
                                pyoxigraph 0.5.x has no RDFS entailment, so
                                `cataforge kg init` (sub-PR 2) loads this at store
                                bootstrap. See spike-2 §2.1 (issue #142).

Encoding: forces PYTHONIOENCODING=utf-8 in os.environ so any linkml internals
that shell out do not hit the Windows GBK UnicodeEncodeError from spike-1 §1.4.
This script itself writes via Path.write_text(..., encoding="utf-8") and never
relies on stdout encoding.

Idempotency: subclass_axioms.ttl is byte-identical across runs (sorted triples,
no timestamps). The Pydantic / SHACL outputs are deterministic-modulo-LinkML;
a `# Generation date:` header line is stripped so unrelated reruns do not
churn diffs.

Usage:
    python scripts/codegen_kg_schema.py
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ.setdefault("PYTHONIOENCODING", "utf-8")

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from cataforge.utils.common import ensure_utf8  # noqa: E402

ensure_utf8()

SCHEMA_DIR = REPO_ROOT / "src" / "cataforge" / "kg" / "schemas"

DEFAULT_OUT_DIR = REPO_ROOT / "src" / "cataforge" / "kg" / "_generated"

CORE_YAML = SCHEMA_DIR / "core.yaml"
GOVERNANCE_YAML = SCHEMA_DIR / "governance.yaml"


def _strip_timestamps(text: str) -> str:
    keep = []
    for line in text.splitlines(keepends=True):
        if line.lstrip().startswith("# Generation date:"):
            continue
        keep.append(line)
    return "".join(keep)


def gen_pydantic(yaml_path: Path, out_path: Path) -> None:
    from linkml.generators.pydanticgen import PydanticGenerator

    gen = PydanticGenerator(str(yaml_path))
    out_path.write_text(_strip_timestamps(gen.serialize()), encoding="utf-8")


def gen_shacl(yaml_path: Path, out_path: Path) -> None:
    from linkml.generators.shaclgen import ShaclGenerator

    gen = ShaclGenerator(str(yaml_path))
    out_path.write_text(_strip_timestamps(gen.serialize()), encoding="utf-8")


def gen_subclass_axioms(yaml_paths: list[Path], out_path: Path) -> None:
    from cataforge.kg._schema_axioms import iter_subclass_axioms, prefix_map

    namespaces = prefix_map(yaml_paths)
    pairs = list(iter_subclass_axioms(yaml_paths))

    lines: list[str] = [
        "# Auto-generated by scripts/codegen_kg_schema.py — do not edit.",
        "# Materializes the LinkML `is_a` chain as rdfs:subClassOf triples so",
        "# pyoxigraph property-path queries (a/rdfs:subClassOf*) traverse the",
        "# class hierarchy. Loaded by `cataforge kg init` at store bootstrap.",
        "",
    ]
    for prefix in sorted(namespaces):
        lines.append(f"@prefix {prefix}: <{namespaces[prefix]}> .")
    lines.append("")

    for child, parent in pairs:
        lines.append(f"{child} rdfs:subClassOf {parent} .")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def codegen(target_dir: Path) -> list[Path]:
    target_dir.mkdir(parents=True, exist_ok=True)
    artifacts: list[Path] = []

    for yaml_path, py_name, ttl_name in [
        (CORE_YAML, "core_pydantic.py", "core_shapes.ttl"),
        (GOVERNANCE_YAML, "governance_pydantic.py", "governance_shapes.ttl"),
    ]:
        py_out = target_dir / py_name
        ttl_out = target_dir / ttl_name
        gen_pydantic(yaml_path, py_out)
        gen_shacl(yaml_path, ttl_out)
        artifacts += [py_out, ttl_out]

    subclass_out = target_dir / "subclass_axioms.ttl"
    gen_subclass_axioms([CORE_YAML, GOVERNANCE_YAML], subclass_out)
    artifacts.append(subclass_out)
    return artifacts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="LinkML → Pydantic + SHACL + rdfs:subClassOf codegen for cataforge.kg",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help="output directory (default: src/cataforge/kg/_generated)",
    )
    args = parser.parse_args(argv)

    for required in (CORE_YAML, GOVERNANCE_YAML):
        if not required.exists():
            print(f"[FAIL] schema source missing: {required}", file=sys.stderr)
            return 1

    artifacts = codegen(args.out)
    for path in artifacts:
        try:
            rel = path.relative_to(REPO_ROOT)
        except ValueError:
            rel = path
        print(f"[OK] {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
