"""CataForge Penpot integration — Docker Compose deployment + MCP Server management.

Invoked via ``cataforge penpot [deploy|mcp-only|start|stop|status]``.
"""

from __future__ import annotations

import contextlib
import os
import secrets
import shutil
import signal
import subprocess
import sys
import tempfile
import textwrap
import time
import urllib.error
import urllib.request
from collections.abc import Callable
from typing import Any

from cataforge.cli.errors import CataforgeError
from cataforge.utils.common import (
    BOLD,
    CYAN,
    DIM,
    GREEN,
    NC,
    RED,
    YELLOW,
    detect_platform,
    ensure_utf8_stdio,
    fail,
    find_available_port,
    get_command_version,
    has_command,
    info,
    is_port_listening,
    load_dotenv,
    ok,
    run_cmd,
    section,
    warn,
)
from cataforge.utils.docker_util import (
    docker_compose_cmd,
    ensure_docker_running,
    pull_all_images_from_compose_file,
)
from cataforge.utils.run_subprocess import run as run_proc

PLATFORM = detect_platform()

DEFAULT_PENPOT_PORT = 9001
DEFAULT_MCP_PORT = 4401
DEFAULT_PLUGIN_PORT = 4400

# Pin to a Penpot release whose frontend image and MCP server are known to
# agree. ``latest`` floats and has burned users when the upstream monorepo
# adds new build-script-bearing dependencies that pnpm 10+ refuses by default.
DEFAULT_MCP_PACKAGE_VERSION = "latest"

# Pin every ``penpotapp/*`` container image (frontend / backend / exporter /
# mcp) to a known-good upstream release. ``latest`` floats and has caused
# silent breakage when new required services (e.g. ``penpot-mcp`` in 2.15)
# appeared in upstream's reference compose without matching changes here.
# Override with ``PENPOT_IMAGE_TAG=<tag>`` to follow a different release.
DEFAULT_PENPOT_IMAGE_TAG = "2.15"

# Node major versions @penpot/mcp upstream tests against. Outside this range
# we still let the user proceed (warn only) — pinning hard is too aggressive
# given how often Node majors shift on developer machines.
SUPPORTED_NODE_MAJORS = (20, 22)

HEALTH_TIMEOUT = 60
MCP_HEALTH_TIMEOUT = 120

DOCKER_REGISTRY_MIRRORS = [
    "",
    "docker.xuanyuan.me",
    "docker.m.daocloud.io",
    "mirror.ccs.tencentyun.com",
]

_TMPDIR = tempfile.gettempdir()
MCP_PID_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.pid")
MCP_LOG_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.log")


# ---------------------------------------------------------------------------
# Docker Compose template
# ---------------------------------------------------------------------------

DOCKER_COMPOSE_TEMPLATE = textwrap.dedent("""\
    ## Penpot Docker Compose — auto-generated by CataForge
    networks:
      penpot:
    volumes:
      penpot_postgres_v15:
      penpot_assets:
    services:
      penpot-frontend:
        image: penpotapp/frontend:{image_tag}
        restart: always
        ports:
          - "{penpot_port}:8080"
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          - penpot-backend
          - penpot-exporter
          - penpot-mcp
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
      penpot-backend:
        image: penpotapp/backend:{image_tag}
        restart: always
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          penpot-postgres:
            condition: service_healthy
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://localhost:{penpot_port}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
          - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
          - PENPOT_DATABASE_USERNAME=penpot
          - PENPOT_DATABASE_PASSWORD=penpot
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
          - PENPOT_OBJECTS_STORAGE_BACKEND=fs
          - PENPOT_OBJECTS_STORAGE_FS_DIRECTORY=/opt/data/assets
          - PENPOT_TELEMETRY_ENABLED=false
          - PENPOT_SMTP_DEFAULT_FROM=no-reply@penpot.local
          - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@penpot.local
          - PENPOT_SMTP_HOST=penpot-mailcatch
          - PENPOT_SMTP_PORT=1025
          - PENPOT_SMTP_TLS=false
          - PENPOT_SMTP_SSL=false
      penpot-exporter:
        image: penpotapp/exporter:{image_tag}
        restart: always
        depends_on:
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
      penpot-mcp:
        image: penpotapp/mcp:{image_tag}
        restart: always
        networks:
          - penpot
      penpot-postgres:
        image: postgres:15
        restart: always
        stop_signal: SIGINT
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U penpot"]
          interval: 2s
          timeout: 10s
          retries: 5
          start_period: 2s
        volumes:
          - penpot_postgres_v15:/var/lib/postgresql/data
        networks:
          - penpot
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=penpot
          - POSTGRES_USER=penpot
          - POSTGRES_PASSWORD=penpot
      penpot-valkey:
        image: valkey/valkey:8.1
        restart: always
        healthcheck:
          test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
          interval: 1s
          timeout: 3s
          retries: 5
          start_period: 3s
        networks:
          - penpot
        environment:
          - VALKEY_EXTRA_FLAGS=--maxmemory 128mb --maxmemory-policy volatile-lfu
      penpot-mailcatch:
        image: sj26/mailcatcher:latest
        restart: always
        expose:
          - "1025"
        ports:
          - "1080:1080"
        networks:
          - penpot
""")


def get_config() -> dict[str, Any]:
    return {
        "penpot_dir": os.environ.get(
            "PENPOT_INSTALL_DIR",
            os.path.join(os.path.expanduser("~"), "penpot-docker"),
        ),
        "penpot_port": int(os.environ.get("PENPOT_PORT", DEFAULT_PENPOT_PORT)),
        "mcp_port": int(os.environ.get("PENPOT_MCP_SERVER_PORT", DEFAULT_MCP_PORT)),
        "plugin_port": int(os.environ.get("PENPOT_MCP_PLUGIN_PORT", DEFAULT_PLUGIN_PORT)),
        "penpot_flags": os.environ.get(
            "PENPOT_FLAGS",
            "enable-login-with-password disable-email-verification "
            "enable-smtp enable-prepl-server disable-secure-session-cookies",
        ),
        "mcp_version": os.environ.get(
            "PENPOT_MCP_VERSION", DEFAULT_MCP_PACKAGE_VERSION
        ),
        "image_tag": os.environ.get("PENPOT_IMAGE_TAG", DEFAULT_PENPOT_IMAGE_TAG),
    }


def _extract_secret_key(compose_file: str) -> str | None:
    try:
        with open(compose_file, encoding="utf-8") as f:
            for line in f:
                if "PENPOT_SECRET_KEY=" in line:
                    val = line.split("=", 1)[1].strip()
                    if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
                        val = val[1:-1]
                    return val
    except OSError:
        pass
    return None


def _generate_compose_file(config: dict, force: bool = False) -> str:
    compose_dir = config["penpot_dir"]
    os.makedirs(compose_dir, exist_ok=True)
    compose_file = os.path.join(compose_dir, "docker-compose.yml")
    if os.path.isfile(compose_file) and not force:
        info(f"docker-compose.yml 已存在: {compose_file}")
        return compose_file
    existing = _extract_secret_key(compose_file) if os.path.isfile(compose_file) else None
    secret_key = existing or secrets.token_hex(32)
    content = DOCKER_COMPOSE_TEMPLATE.format(
        penpot_port=config["penpot_port"],
        penpot_flags=config["penpot_flags"],
        secret_key=secret_key,
        image_tag=config["image_tag"],
    )
    with open(compose_file, "w", encoding="utf-8") as f:
        f.write(content)
    ok(f"{'已重新生成' if force else '已生成'} docker-compose.yml: {compose_file}")
    return compose_file


def _is_penpot_container_running() -> bool:
    try:
        r = run_proc(
            ["docker", "ps", "--filter", "name=penpot", "--format", "{{.Names}}"],
            timeout=10,
        )
        return bool(r.stdout.strip())
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def _is_penpot_running(config: dict) -> bool:
    return _is_penpot_container_running() and is_port_listening(config["penpot_port"])


def _node_major(version_str: str) -> int | None:
    """Parse the leading integer of a ``node --version`` output (``v22.11.0``)."""
    s = version_str.strip().lstrip("v")
    head = s.split(".", 1)[0]
    try:
        return int(head)
    except ValueError:
        return None


def preflight_check(scope: str = "all") -> bool:
    section("依赖预检")
    passed = True
    if scope == "all":
        if not has_command("docker"):
            fail("Docker 未安装。请安装: https://docs.docker.com/get-docker/")
            passed = False
        else:
            ok(f"Docker {DIM}({get_command_version(['docker', '--version'])}){NC}")
        dc_cmd = docker_compose_cmd()
        if not dc_cmd:
            fail("Docker Compose 未安装。")
            passed = False
        else:
            ok(f"Docker Compose {DIM}({get_command_version(dc_cmd + ['version'])}){NC}")
    if not has_command("node"):
        fail("Node.js 未安装。请安装: https://nodejs.org (推荐 v22 LTS)")
        passed = False
    else:
        node_ver = get_command_version(["node", "--version"])
        major = _node_major(node_ver)
        lo, hi = SUPPORTED_NODE_MAJORS[0], SUPPORTED_NODE_MAJORS[-1]
        if major is None or not (lo <= major <= hi):
            warn(
                f"Node.js {node_ver} 不在 @penpot/mcp 兼容范围 "
                f"(v{lo}–v{hi})；如启动失败请改用 v22 LTS"
            )
        else:
            ok(f"Node.js {DIM}({node_ver}){NC}")
    if not has_command("npx"):
        fail("npx 未找到")
        passed = False
    else:
        ok("npx")
    if not passed:
        fail("依赖预检未通过")
    return passed


def deploy_penpot(config: dict) -> bool:
    section("部署 Penpot (Docker Compose)")
    if not ensure_docker_running():
        return False
    if _is_penpot_running(config):
        ok("Penpot 已在运行，跳过部署")
        return True
    orig_port = config["penpot_port"]
    config["penpot_port"] = find_available_port(orig_port, "Penpot Frontend")
    dc_cmd = docker_compose_cmd()
    compose_file = _generate_compose_file(config, force=(config["penpot_port"] != orig_port))
    compose_dir = os.path.dirname(compose_file)
    info("拉取 Docker 镜像...")
    if not pull_all_images_from_compose_file(compose_file, DOCKER_REGISTRY_MIRRORS):
        fail("一个或多个 Docker 镜像拉取失败，已中止部署")
        return False
    info("启动 Penpot 服务...")
    up_result = run_proc(
        dc_cmd + ["-f", compose_file, "up", "-d"],
        cwd=compose_dir,
        timeout=120,
        capture_output=False,
    )
    if up_result.returncode != 0:
        fail("Docker Compose 启动失败")
        return False
    info(f"等待 Penpot 就绪 (最多 {HEALTH_TIMEOUT}s)...")
    for _i in range(HEALTH_TIMEOUT):
        if _is_penpot_running(config):
            ok(f"Penpot 就绪 {DIM}-> http://localhost:{config['penpot_port']}{NC}")
            return True
        time.sleep(1)
    warn(f"Penpot 在 {HEALTH_TIMEOUT}s 内未就绪")
    return False


# ---------------------------------------------------------------------------
# MCP Server management
# ---------------------------------------------------------------------------


def _read_mcp_pid() -> int | None:
    if not os.path.isfile(MCP_PID_FILE):
        return None
    try:
        with open(MCP_PID_FILE, encoding="utf-8") as f:
            return int(f.read().strip())
    except (ValueError, OSError):
        return None


def _write_mcp_pid(pid: int) -> None:
    with open(MCP_PID_FILE, "w", encoding="utf-8") as f:
        f.write(str(pid))


def _remove_mcp_pid() -> None:
    with contextlib.suppress(OSError):
        os.remove(MCP_PID_FILE)


def _is_mcp_running(config: dict) -> bool:
    try:
        req = urllib.request.Request(f"http://localhost:{config['mcp_port']}/mcp", method="GET")
        # 2s is deliberate: this probe runs on every `penpot status` /
        # `penpot ensure` / Penpot skill warm-up and must fail-fast on
        # "server not up" without making the user wait. A higher
        # timeout would make those entry points feel hung when MCP
        # isn't installed yet — the failure mode we're checking for.
        # Do NOT raise without a corresponding adjustment in
        # ``cmd_ensure`` / ``cmd_status`` UX.
        urllib.request.urlopen(req, timeout=2)
        return True
    except urllib.error.HTTPError:
        return True
    except (urllib.error.URLError, OSError, TimeoutError):
        return False


def _is_process_alive(pid: int) -> bool:
    try:
        if PLATFORM == "windows":
            r = run_proc(["tasklist", "/FI", f"PID eq {pid}"], timeout=5)
            return str(pid) in r.stdout
        else:
            os.kill(pid, 0)
            return True
    except (OSError, subprocess.TimeoutExpired):
        return False


def _mcp_npx_env(config: dict) -> dict[str, str]:
    """Environment for the npx-spawned @penpot/mcp process.

    PNPM_CONFIG_STRICT_DEP_BUILDS=false demotes ERR_PNPM_IGNORED_BUILDS (raised
    by pnpm 10+ when esbuild/sharp's build scripts are not pre-approved) into
    a warning so the monorepo install can finish.
    """
    env = os.environ.copy()
    env["PORT"] = str(config["mcp_port"])
    env["PLUGIN_PORT"] = str(config["plugin_port"])
    env["PNPM_CONFIG_STRICT_DEP_BUILDS"] = "false"
    env["npm_config_strict_dep_builds"] = "false"
    env["COREPACK_ENABLE_DOWNLOAD_PROMPT"] = "0"
    return env


def start_mcp(config: dict) -> bool:
    section("启动 MCP Server")
    if _is_mcp_running(config):
        ok(f"MCP Server 已在端口 {config['mcp_port']} 运行")
        return True
    config["mcp_port"] = find_available_port(config["mcp_port"], "MCP Server")
    config["plugin_port"] = find_available_port(config["plugin_port"], "Plugin Server")
    env = _mcp_npx_env(config)
    mcp_version = config.get("mcp_version") or DEFAULT_MCP_PACKAGE_VERSION
    package_spec = f"@penpot/mcp@{mcp_version}"
    info(f"通过 npx {package_spec} 启动 MCP Server...")
    # Resolve npx to full path so we can avoid shell=True on Windows
    # (npx is typically `npx.cmd`, which Popen otherwise can't locate without the shell).
    npx_path = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx_path:
        fail("未找到 npx 命令，请先安装 Node.js")
        return False
    cmd = [npx_path, "--yes", package_spec]
    with open(MCP_LOG_FILE, "wb") as log_fh:
        if PLATFORM == "windows":
            proc = subprocess.Popen(  # allow-raw-subprocess: long-running MCP server
                cmd, stdout=log_fh, stderr=subprocess.STDOUT,
                env=env,
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
            )
        else:
            proc = subprocess.Popen(  # allow-raw-subprocess: long-running MCP server
                cmd, stdout=log_fh, stderr=subprocess.STDOUT,
                env=env, start_new_session=True,
            )
    _write_mcp_pid(proc.pid)
    info(f"等待 MCP Server 就绪 (最多 {MCP_HEALTH_TIMEOUT}s)...")
    for _i in range(MCP_HEALTH_TIMEOUT):
        if _is_mcp_running(config):
            ok(f"MCP Server 就绪 {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
            return True
        if proc.poll() is not None:
            _report_mcp_failure(proc.returncode)
            _remove_mcp_pid()
            return False
        time.sleep(1)
    warn(f"MCP Server 在 {MCP_HEALTH_TIMEOUT}s 内未就绪")
    return False


def _report_mcp_failure(exit_code: int | None) -> None:
    """Print a tail of the MCP log plus a diagnosis for common failure modes."""
    fail(f"MCP Server 进程已退出 (exit={exit_code})")
    tail = _tail_log(MCP_LOG_FILE, lines=20)
    if tail:
        print(f"\n  {DIM}日志尾段 ({MCP_LOG_FILE}):{NC}")
        for line in tail:
            print(f"    {DIM}{line}{NC}")
    diagnosis = _diagnose_mcp_log("\n".join(tail))
    if diagnosis:
        print()
        for line in diagnosis:
            print(f"  {line}")


def _tail_log(path: str, *, lines: int = 20) -> list[str]:
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            buf = f.readlines()
    except OSError:
        return []
    return [line.rstrip("\r\n") for line in buf[-lines:]]


def _diagnose_mcp_log(text: str) -> list[str]:
    """Return human-readable hints for known MCP startup failures.

    Backed by :mod:`cataforge.cli.diagnostics` so adding/editing a pattern
    updates both ``penpot start`` failure reports and ``penpot doctor``
    at the same time. Returns a flat list of strings to stay backward-
    compatible with the prior signature (callers use ``"\\n".join`` for
    log-style assertions).
    """
    from cataforge.cli.diagnostics import PENPOT_PATTERNS
    from cataforge.cli.ui import _pattern_matches

    hints: list[str] = []
    for p in PENPOT_PATTERNS:
        if not _pattern_matches(p.needle, text):
            continue
        hints.append(f"{YELLOW}诊断{NC}: {p.diagnosis}")
        fix_line = f"{YELLOW}修复{NC}: {p.fix_action}"
        if p.fix_command:
            fix_line += f"\n         → {BOLD}{p.fix_command}{NC}"
        hints.append(fix_line)
        # Only report the first matching pattern to avoid noise — the
        # original implementation used elif/elif so callers depend on this.
        break
    return hints


def stop_mcp(config: dict) -> bool:
    pid = _read_mcp_pid()
    if pid and _is_process_alive(pid):
        info(f"停止 MCP Server (PID: {pid})...")
        try:
            if PLATFORM == "windows":
                # taskkill is part of every supported Windows SKU but is
                # absent from stripped images (Nano Server, some CI
                # containers). Fail loudly rather than swallow the
                # FileNotFoundError into the bare ``except OSError``
                # below and leave the user looking at "stopped" output
                # with the process still alive.
                if not shutil.which("taskkill"):
                    raise CataforgeError(
                        "taskkill not found on PATH — required to stop the "
                        f"Penpot MCP server (PID {pid}) on Windows. Install "
                        "the Windows admin tools (taskkill ships with every "
                        "Pro/Enterprise SKU) or stop the process manually."
                    )
                run_proc(
                    ["taskkill", "/F", "/T", "/PID", str(pid)],
                    timeout=10,
                )
            else:
                os.kill(pid, signal.SIGTERM)
                for _ in range(10):
                    if not _is_process_alive(pid):
                        break
                    time.sleep(0.5)
                else:
                    os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
        _remove_mcp_pid()
        ok("MCP Server 已停止")
        return True
    if _is_mcp_running(config):
        warn(f"端口 {config['mcp_port']} 仍有服务，但无 PID 记录")
        _remove_mcp_pid()
        return False
    info("MCP Server 未在运行")
    _remove_mcp_pid()
    return True


def register_claude_mcp(config: dict) -> None:
    section("注册 MCP 到 Claude Code")
    mcp_url = f"http://localhost:{config['mcp_port']}/mcp"
    if not has_command("claude"):
        info(
            f"Claude Code CLI 未检测到，请手动注册:\n"
            f"    {BOLD}claude mcp add penpot -t http {mcp_url}{NC}"
        )
        return
    result = run_cmd(["claude", "mcp", "list"], timeout=10)
    if result.returncode == 0 and result.stdout and "penpot" in result.stdout.lower():
        ok("Claude Code 已注册 penpot MCP")
        return
    result = run_cmd(["claude", "mcp", "add", "penpot", "-t", "http", mcp_url], timeout=10)
    stdout = result.stdout or ""
    if result.returncode == 0 or "Added" in stdout or "already" in stdout:
        ok("已注册到 Claude Code")
    else:
        warn(f"自动注册失败，请手动执行: claude mcp add penpot -t http {mcp_url}")


# ---------------------------------------------------------------------------
# Sub-commands
# ---------------------------------------------------------------------------


def print_header(title: str, subtitle: str | None = None) -> None:
    """Render a consistent two-line banner above each sub-command's output."""
    bar = "━" * max(len(title) + 4, 50)
    print(f"\n{CYAN}{BOLD}━━ {title} {bar}{NC}")
    if subtitle:
        print(f"  {DIM}{subtitle}{NC}")
    print()


def cmd_deploy(config: dict) -> int:
    print_header(
        "Penpot 完整部署",
        "Docker 自托管 (frontend + backend + exporter + postgres + valkey + mailcatch) + MCP",
    )
    if not preflight_check("all"):
        return 1
    if not deploy_penpot(config):
        fail("Penpot 部署失败")
        return 1
    if not start_mcp(config):
        warn("MCP Server 启动异常")
    register_claude_mcp(config)
    return 0


def cmd_mcp_only(config: dict) -> int:
    print_header("Penpot MCP Server 部署", "只起 MCP — 假定 Penpot 已运行")
    if not preflight_check("mcp"):
        return 1
    penpot_base = os.environ.get("PENPOT_BASE_URL", "")
    is_remote = penpot_base and not any(h in penpot_base for h in ("localhost", "127.0.0.1"))
    if is_remote:
        info(f"将连接到远程 Penpot 实例: {penpot_base}")
    elif not _is_penpot_running(config):
        warn(f"Penpot 未在端口 {config['penpot_port']} 运行")
    if not start_mcp(config):
        return 1
    register_claude_mcp(config)
    return 0


# ---------------------------------------------------------------------------
# Remote (SaaS) — design.penpot.app + local MCP server
# ---------------------------------------------------------------------------

PENPOT_SAAS_URL = "https://design.penpot.app"


def print_remote_onboarding(config: dict) -> None:
    """Walk the user through loading the MCP plugin into design.penpot.app.

    The MCP server itself talks to Penpot via a WebSocket-connected browser
    plugin (not the REST API), so the SaaS flow requires the user to load the
    plugin manifest into the Penpot UI exactly once per browser session.
    """
    plugin_manifest = (
        f"http://localhost:{config['plugin_port']}/manifest.json"
    )
    mcp_endpoint = f"http://localhost:{config['mcp_port']}/mcp"
    section("浏览器侧设置（必须完成才能让 LLM 看到设计）")
    steps = [
        f"在浏览器打开 {BOLD}{PENPOT_SAAS_URL}{NC} 并登录",
        "打开任意设计文件 → 点击右上角 Plugins 图标",
        f"在 'Plugin manager' 粘贴: {BOLD}{plugin_manifest}{NC}",
        "点击 Install，再点 Open，最后点 Connect to MCP server",
        f"状态变 Connected 即可在 LLM 端使用 MCP 工具 ({DIM}{mcp_endpoint}{NC})",
    ]
    for n, msg in enumerate(steps, start=1):
        print(f"  {CYAN}{n}.{NC} {msg}")
    print(
        f"\n  {DIM}提示: Chrome 142+ 会弹出 'Private Network Access' 授权框，"
        f"允许即可；Brave 需要对 design.penpot.app 关闭 Shield。{NC}"
    )
    print(
        f"  {DIM}插件 UI 关闭后 WebSocket 会断开 — 让 Plugin 面板保持打开。{NC}\n"
    )


def cmd_remote(config: dict) -> int:
    """Remote (SaaS) mode: only launch local MCP, point user at design.penpot.app."""
    print_header(
        "Penpot Remote (SaaS) + 本地 MCP",
        f"使用 {PENPOT_SAAS_URL} 作为 Penpot 后端 — 无需 Docker 自托管",
    )
    if not preflight_check("mcp"):
        return 1
    if not start_mcp(config):
        return 1
    register_claude_mcp(config)
    print_remote_onboarding(config)
    return 0


def cmd_start(config: dict) -> int:
    print_header("启动 Penpot 服务")
    if not preflight_check("all"):
        return 1
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = docker_compose_cmd()
        if dc_cmd and ensure_docker_running():
            run_proc(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"],
                timeout=120,
                capture_output=False,
            )
    start_mcp(config)
    return 0


def cmd_stop(config: dict) -> int:
    print_header("停止 Penpot 服务")
    section("停止 MCP Server")
    stop_mcp(config)
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = docker_compose_cmd()
        if dc_cmd:
            section("停止 Penpot (Docker)")
            run_proc(
                dc_cmd + ["-f", compose_file, "down"],
                cwd=config["penpot_dir"],
                timeout=120,
                capture_output=False,
            )
    return 0


def _status_rows(config: dict) -> list[tuple[str, bool, str]]:
    """Probe every Penpot-side service. Returned as (label, up, endpoint)."""
    return [
        (
            "Penpot Frontend",
            _is_penpot_running(config),
            f"http://localhost:{config['penpot_port']}",
        ),
        (
            "MCP Server",
            _is_mcp_running(config),
            f"http://localhost:{config['mcp_port']}/mcp",
        ),
        (
            "Plugin Server",
            is_port_listening(config["plugin_port"]),
            f"http://localhost:{config['plugin_port']}",
        ),
    ]


def _print_status_table(rows: list[tuple[str, bool, str]]) -> None:
    """Pretty-print the service probe results as an aligned three-column table."""
    label_w = max(len(r[0]) for r in rows) + 2
    state_w = 8
    print(f"  {BOLD}{'服务':<{label_w}}{'状态':<{state_w}}端点{NC}")
    print(f"  {DIM}{'─' * (label_w + state_w + 40)}{NC}")
    for label, up, endpoint in rows:
        state = f"{GREEN}✔ Up{NC}    " if up else f"{RED}✖ Down{NC}  "
        print(f"  {label:<{label_w}}{state:<{state_w}}{DIM}{endpoint}{NC}")


def cmd_status(config: dict) -> int:
    print_header("Penpot 服务状态")
    rows = _status_rows(config)
    _print_status_table(rows)
    mcp_up = rows[1][1]
    if not mcp_up:
        print(
            f"\n  下一步: "
            f"{BOLD}cataforge penpot init{NC}（交互向导）或 "
            f"{BOLD}cataforge penpot remote{NC} / "
            f"{BOLD}cataforge penpot deploy{NC}\n"
        )
    else:
        print()
    return 0


# ---------------------------------------------------------------------------
# Interactive init wizard
# ---------------------------------------------------------------------------

MODE_REMOTE = "remote"
MODE_LOCAL = "local"
MODE_MCP_ONLY = "mcp-only"

_MODE_KEY_TO_NAME = {"1": MODE_REMOTE, "2": MODE_LOCAL, "3": MODE_MCP_ONLY}
_MODE_NAME_TO_KEY = {v: k for k, v in _MODE_KEY_TO_NAME.items()}


def _prompt_mode(default: str = MODE_REMOTE) -> str:
    """Prompt the user to pick a Penpot integration mode."""
    from cataforge.cli.ui import ChoiceOption
    from cataforge.cli.ui import ui as _ui

    options = [
        ChoiceOption(
            key="1",
            label="Remote",
            icon="☁",
            description="design.penpot.app + 本地 MCP — 最快上手，零 Docker，需 Penpot 账号",
        ),
        ChoiceOption(
            key="2",
            label="Local",
            icon="⚙",
            description="全量自托管 (6 容器 + MCP) — 数据自己管，需 Docker + ~3GB 镜像",
        ),
        ChoiceOption(
            key="3",
            label="MCP only",
            icon="🔌",
            description="只起 MCP，自己接已有 Penpot 实例（自托管或他人共享）",
        ),
    ]
    chosen = _ui.prompt_choice(
        "选择 Penpot 集成模式",
        options,
        default=_MODE_NAME_TO_KEY[default],
    )
    return _MODE_KEY_TO_NAME[chosen]


def cmd_init(config: dict) -> int:
    """Interactive setup wizard — picks Remote / Local / MCP-only and dispatches."""
    print_header(
        "Penpot 集成向导",
        "为新用户挑选最合适的部署模式",
    )
    mode = _prompt_mode()
    print()
    if mode == MODE_REMOTE:
        return cmd_remote(config)
    if mode == MODE_LOCAL:
        return cmd_deploy(config)
    return cmd_mcp_only(config)


# ---------------------------------------------------------------------------
# Doctor — diagnose + auto-fix common Penpot integration failures
# ---------------------------------------------------------------------------


def cmd_doctor(config: dict) -> int:
    """Inspect compose file, MCP log, and service ports; suggest fixes."""
    print_header("Penpot 服务诊断")
    problems: list[str] = []
    actions: list[str] = []

    section("环境检查")
    if has_command("node"):
        node_ver = get_command_version(["node", "--version"])
        major = _node_major(node_ver)
        lo, hi = SUPPORTED_NODE_MAJORS[0], SUPPORTED_NODE_MAJORS[-1]
        if major is None or not (lo <= major <= hi):
            warn(f"Node.js {node_ver} 不在兼容范围 v{lo}–v{hi}")
            problems.append("node-version")
            actions.append("安装 Node v22 LTS（推荐通过 nvm/volta 管理）")
        else:
            ok(f"Node.js {node_ver}")
    else:
        fail("Node.js 未安装")
        problems.append("node-missing")
        actions.append("https://nodejs.org 安装 v22 LTS")

    section("compose 模板检查")
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        try:
            with open(compose_file, encoding="utf-8") as fh:
                content = fh.read()
        except OSError:
            content = ""
        tag = config["image_tag"]
        if "penpot-mcp:" in content and f":{tag}" in content:
            ok(f"compose 含 penpot-mcp 服务且 image tag 已固定为 {tag}")
        else:
            warn(
                f"compose 文件缺少 penpot-mcp 服务或未固定 image tag ({tag}) — "
                f"2.15 frontend 要求 penpot-mcp upstream 才能启动"
            )
            problems.append("compose-stale")
            actions.append(
                "运行 `cataforge penpot deploy --force-recreate` "
                "重写 compose 文件"
            )
    else:
        info(f"未找到 compose 文件: {compose_file}")

    section("MCP 日志检查")
    if os.path.isfile(MCP_LOG_FILE):
        tail = _tail_log(MCP_LOG_FILE, lines=80)
        hints = _diagnose_mcp_log("\n".join(tail))
        if hints:
            for line in hints:
                print(f"  {line}")
            problems.append("mcp-startup")
        else:
            ok("MCP 日志未发现已知错误模式")
    else:
        info(f"未找到 MCP 日志: {MCP_LOG_FILE} (MCP 可能从未启动)")

    section("运行状态")
    rows = _status_rows(config)
    _print_status_table(rows)

    print()
    if not problems:
        ok("未发现已知问题")
        return 0
    section("修复建议")
    for n, msg in enumerate(actions, start=1):
        print(f"  {CYAN}{n}.{NC} {msg}")
    print()
    return 1


def cmd_ensure(config: dict) -> int:
    if _is_mcp_running(config):
        print(f"Penpot MCP already running on port {config['mcp_port']}")
        return 0
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        if has_command("docker") and not ensure_docker_running():
            fail("Docker daemon 无法启动")
            return 1
        dc_cmd = docker_compose_cmd()
        if dc_cmd and not _is_penpot_running(config):
            run_proc(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"],
                timeout=120,
            )
            for _ in range(30):
                if _is_penpot_running(config):
                    break
                time.sleep(1)
    if start_mcp(config):
        return 0
    fail("Penpot MCP not installed. Run: cataforge penpot deploy")
    return 1


# ---------------------------------------------------------------------------
# Public handler registry
# ---------------------------------------------------------------------------
#
# Maps user-facing subcommand name → handler callable. Both the Click
# wrapper in ``cli/penpot_cmd.py`` and the ``__main__`` argparse entry
# point look subcommands up here. Centralising the dispatch table
# replaces an earlier ``getattr(penpot, handler_name)`` lookup whose
# string parameters duplicated the same mapping in two places and
# silently AttributeError'd if a function was renamed.
HANDLERS: dict[str, Callable[[dict], int]] = {
    "init": cmd_init,
    "deploy": cmd_deploy,
    "mcp-only": cmd_mcp_only,
    "remote": cmd_remote,
    "start": cmd_start,
    "stop": cmd_stop,
    "status": cmd_status,
    "doctor": cmd_doctor,
    "ensure": cmd_ensure,
}


# ---------------------------------------------------------------------------
# CLI entry (for use as python -m cataforge.integrations.penpot)
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    import argparse

    ensure_utf8_stdio()
    load_dotenv(set_env=True)

    parser = argparse.ArgumentParser(description="CataForge Penpot integration")
    parser.add_argument(
        "command", nargs="?",
        choices=[
            "init", "deploy", "mcp-only", "remote",
            "start", "stop", "status", "doctor",
        ],
    )
    parser.add_argument("--ensure", action="store_true")
    args = parser.parse_args(argv)
    config = get_config()

    if args.ensure:
        return HANDLERS["ensure"](config)
    if not args.command:
        parser.print_help()
        return 0
    return HANDLERS[args.command](config)


if __name__ == "__main__":
    sys.exit(main())
