"""CataForge Penpot integration — Docker Compose deployment + MCP Server management.

Invoked via ``cataforge penpot [deploy|mcp-only|start|stop|status]``.
"""

from __future__ import annotations

import contextlib
import os
import secrets
import signal
import subprocess
import sys
import tempfile
import textwrap
import time
import urllib.error
import urllib.request
from typing import Any

from cataforge.utils.common import (
    BOLD,
    CYAN,
    DIM,
    NC,
    detect_platform,
    ensure_utf8_stdio,
    fail,
    find_available_port,
    get_command_version,
    has_command,
    info,
    is_port_listening,
    load_dotenv,
    ok,
    run_cmd,
    section,
    warn,
)
from cataforge.utils.docker_util import (
    docker_compose_cmd,
    ensure_docker_running,
    pull_all_images_from_compose_file,
)

PLATFORM = detect_platform()

DEFAULT_PENPOT_PORT = 9001
DEFAULT_MCP_PORT = 4401
DEFAULT_PLUGIN_PORT = 4400

HEALTH_TIMEOUT = 60
MCP_HEALTH_TIMEOUT = 120

DOCKER_REGISTRY_MIRRORS = [
    "",
    "docker.xuanyuan.me",
    "docker.m.daocloud.io",
    "mirror.ccs.tencentyun.com",
]

_TMPDIR = tempfile.gettempdir()
MCP_PID_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.pid")
MCP_LOG_FILE = os.path.join(_TMPDIR, "penpot-mcp-server.log")


# ---------------------------------------------------------------------------
# Docker Compose template
# ---------------------------------------------------------------------------

DOCKER_COMPOSE_TEMPLATE = textwrap.dedent("""\
    ## Penpot Docker Compose — auto-generated by CataForge
    networks:
      penpot:
    volumes:
      penpot_postgres_v15:
      penpot_assets:
    services:
      penpot-frontend:
        image: penpotapp/frontend:latest
        restart: always
        ports:
          - "{penpot_port}:8080"
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          - penpot-backend
          - penpot-exporter
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
      penpot-backend:
        image: penpotapp/backend:latest
        restart: always
        volumes:
          - penpot_assets:/opt/data/assets
        depends_on:
          penpot-postgres:
            condition: service_healthy
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_FLAGS={penpot_flags}
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://localhost:{penpot_port}
          - PENPOT_HTTP_SERVER_MAX_BODY_SIZE=367001600
          - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
          - PENPOT_DATABASE_USERNAME=penpot
          - PENPOT_DATABASE_PASSWORD=penpot
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
          - PENPOT_OBJECTS_STORAGE_BACKEND=fs
          - PENPOT_OBJECTS_STORAGE_FS_DIRECTORY=/opt/data/assets
          - PENPOT_TELEMETRY_ENABLED=false
          - PENPOT_SMTP_DEFAULT_FROM=no-reply@penpot.local
          - PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@penpot.local
          - PENPOT_SMTP_HOST=penpot-mailcatch
          - PENPOT_SMTP_PORT=1025
          - PENPOT_SMTP_TLS=false
          - PENPOT_SMTP_SSL=false
      penpot-exporter:
        image: penpotapp/exporter:latest
        restart: always
        depends_on:
          penpot-valkey:
            condition: service_healthy
        networks:
          - penpot
        environment:
          - PENPOT_SECRET_KEY={secret_key}
          - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
          - PENPOT_REDIS_URI=redis://penpot-valkey/0
      penpot-postgres:
        image: postgres:15
        restart: always
        stop_signal: SIGINT
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U penpot"]
          interval: 2s
          timeout: 10s
          retries: 5
          start_period: 2s
        volumes:
          - penpot_postgres_v15:/var/lib/postgresql/data
        networks:
          - penpot
        environment:
          - POSTGRES_INITDB_ARGS=--data-checksums
          - POSTGRES_DB=penpot
          - POSTGRES_USER=penpot
          - POSTGRES_PASSWORD=penpot
      penpot-valkey:
        image: valkey/valkey:8.1
        restart: always
        healthcheck:
          test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
          interval: 1s
          timeout: 3s
          retries: 5
          start_period: 3s
        networks:
          - penpot
        environment:
          - VALKEY_EXTRA_FLAGS=--maxmemory 128mb --maxmemory-policy volatile-lfu
      penpot-mailcatch:
        image: sj26/mailcatcher:latest
        restart: always
        expose:
          - "1025"
        ports:
          - "1080:1080"
        networks:
          - penpot
""")


def _get_config() -> dict[str, Any]:
    return {
        "penpot_dir": os.environ.get(
            "PENPOT_INSTALL_DIR",
            os.path.join(os.path.expanduser("~"), "penpot-docker"),
        ),
        "penpot_port": int(os.environ.get("PENPOT_PORT", DEFAULT_PENPOT_PORT)),
        "mcp_port": int(os.environ.get("PENPOT_MCP_SERVER_PORT", DEFAULT_MCP_PORT)),
        "plugin_port": int(os.environ.get("PENPOT_MCP_PLUGIN_PORT", DEFAULT_PLUGIN_PORT)),
        "penpot_flags": os.environ.get(
            "PENPOT_FLAGS",
            "enable-login-with-password disable-email-verification "
            "enable-smtp enable-prepl-server disable-secure-session-cookies",
        ),
    }


def _extract_secret_key(compose_file: str) -> str | None:
    try:
        with open(compose_file, encoding="utf-8") as f:
            for line in f:
                if "PENPOT_SECRET_KEY=" in line:
                    val = line.split("=", 1)[1].strip()
                    if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
                        val = val[1:-1]
                    return val
    except OSError:
        pass
    return None


def _generate_compose_file(config: dict, force: bool = False) -> str:
    compose_dir = config["penpot_dir"]
    os.makedirs(compose_dir, exist_ok=True)
    compose_file = os.path.join(compose_dir, "docker-compose.yml")
    if os.path.isfile(compose_file) and not force:
        info(f"docker-compose.yml 已存在: {compose_file}")
        return compose_file
    existing = _extract_secret_key(compose_file) if os.path.isfile(compose_file) else None
    secret_key = existing or secrets.token_hex(32)
    content = DOCKER_COMPOSE_TEMPLATE.format(
        penpot_port=config["penpot_port"],
        penpot_flags=config["penpot_flags"],
        secret_key=secret_key,
    )
    with open(compose_file, "w", encoding="utf-8") as f:
        f.write(content)
    ok(f"{'已重新生成' if force else '已生成'} docker-compose.yml: {compose_file}")
    return compose_file


def _is_penpot_container_running() -> bool:
    try:
        r = subprocess.run(
            ["docker", "ps", "--filter", "name=penpot", "--format", "{{.Names}}"],
            capture_output=True, text=True, timeout=10,
        )
        return bool(r.stdout.strip())
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def _is_penpot_running(config: dict) -> bool:
    return _is_penpot_container_running() and is_port_listening(config["penpot_port"])


def preflight_check(scope: str = "all") -> bool:
    section("依赖预检")
    passed = True
    if scope == "all":
        if not has_command("docker"):
            fail("Docker 未安装。请安装: https://docs.docker.com/get-docker/")
            passed = False
        else:
            ok(f"Docker {DIM}({get_command_version(['docker', '--version'])}){NC}")
        dc_cmd = docker_compose_cmd()
        if not dc_cmd:
            fail("Docker Compose 未安装。")
            passed = False
        else:
            ok(f"Docker Compose {DIM}({get_command_version(dc_cmd + ['version'])}){NC}")
    if not has_command("node"):
        fail("Node.js 未安装。请安装: https://nodejs.org (v18+)")
        passed = False
    else:
        ok(f"Node.js {DIM}({get_command_version(['node', '--version'])}){NC}")
    if not has_command("npx"):
        fail("npx 未找到")
        passed = False
    else:
        ok("npx")
    if not passed:
        fail("依赖预检未通过")
    return passed


def deploy_penpot(config: dict) -> bool:
    section("部署 Penpot (Docker Compose)")
    if not ensure_docker_running():
        return False
    if _is_penpot_running(config):
        ok("Penpot 已在运行，跳过部署")
        return True
    orig_port = config["penpot_port"]
    config["penpot_port"] = find_available_port(orig_port, "Penpot Frontend")
    dc_cmd = docker_compose_cmd()
    compose_file = _generate_compose_file(config, force=(config["penpot_port"] != orig_port))
    compose_dir = os.path.dirname(compose_file)
    info("拉取 Docker 镜像...")
    if not pull_all_images_from_compose_file(compose_file, DOCKER_REGISTRY_MIRRORS):
        fail("一个或多个 Docker 镜像拉取失败，已中止部署")
        return False
    info("启动 Penpot 服务...")
    up_result = subprocess.run(
        dc_cmd + ["-f", compose_file, "up", "-d"],
        cwd=compose_dir, timeout=120,
    )
    if up_result.returncode != 0:
        fail("Docker Compose 启动失败")
        return False
    info(f"等待 Penpot 就绪 (最多 {HEALTH_TIMEOUT}s)...")
    for _i in range(HEALTH_TIMEOUT):
        if _is_penpot_running(config):
            ok(f"Penpot 就绪 {DIM}-> http://localhost:{config['penpot_port']}{NC}")
            return True
        time.sleep(1)
    warn(f"Penpot 在 {HEALTH_TIMEOUT}s 内未就绪")
    return False


# ---------------------------------------------------------------------------
# MCP Server management
# ---------------------------------------------------------------------------


def _read_mcp_pid() -> int | None:
    if not os.path.isfile(MCP_PID_FILE):
        return None
    try:
        with open(MCP_PID_FILE) as f:
            return int(f.read().strip())
    except (ValueError, OSError):
        return None


def _write_mcp_pid(pid: int) -> None:
    with open(MCP_PID_FILE, "w") as f:
        f.write(str(pid))


def _remove_mcp_pid() -> None:
    with contextlib.suppress(OSError):
        os.remove(MCP_PID_FILE)


def _is_mcp_running(config: dict) -> bool:
    try:
        req = urllib.request.Request(f"http://localhost:{config['mcp_port']}/mcp", method="GET")
        urllib.request.urlopen(req, timeout=2)
        return True
    except urllib.error.HTTPError:
        return True
    except (urllib.error.URLError, OSError, TimeoutError):
        return False


def _is_process_alive(pid: int) -> bool:
    try:
        if PLATFORM == "windows":
            r = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}"],
                capture_output=True, text=True, timeout=5,
            )
            return str(pid) in r.stdout
        else:
            os.kill(pid, 0)
            return True
    except (OSError, subprocess.TimeoutExpired):
        return False


def start_mcp(config: dict) -> bool:
    section("启动 MCP Server")
    if _is_mcp_running(config):
        ok(f"MCP Server 已在端口 {config['mcp_port']} 运行")
        return True
    config["mcp_port"] = find_available_port(config["mcp_port"], "MCP Server")
    config["plugin_port"] = find_available_port(config["plugin_port"], "Plugin Server")
    env = os.environ.copy()
    env["PORT"] = str(config["mcp_port"])
    env["PLUGIN_PORT"] = str(config["plugin_port"])
    if "PENPOT_BASE_URL" not in env:
        env["PENPOT_BASE_URL"] = f"http://localhost:{config['penpot_port']}"
    info("通过 npx @penpot/mcp@latest 启动 MCP Server...")
    cmd = ["npx", "--yes", "@penpot/mcp@latest"]
    with open(MCP_LOG_FILE, "wb") as log_fh:
        if PLATFORM == "windows":
            proc = subprocess.Popen(
                cmd, stdout=log_fh, stderr=subprocess.STDOUT,
                env=env, shell=True,
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
            )
        else:
            proc = subprocess.Popen(
                cmd, stdout=log_fh, stderr=subprocess.STDOUT,
                env=env, start_new_session=True,
            )
    _write_mcp_pid(proc.pid)
    info(f"等待 MCP Server 就绪 (最多 {MCP_HEALTH_TIMEOUT}s)...")
    for _i in range(MCP_HEALTH_TIMEOUT):
        if _is_mcp_running(config):
            ok(f"MCP Server 就绪 {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
            return True
        if proc.poll() is not None:
            fail(f"MCP Server 进程已退出 (exit={proc.returncode})")
            _remove_mcp_pid()
            return False
        time.sleep(1)
    warn(f"MCP Server 在 {MCP_HEALTH_TIMEOUT}s 内未就绪")
    return False


def stop_mcp(config: dict) -> bool:
    pid = _read_mcp_pid()
    if pid and _is_process_alive(pid):
        info(f"停止 MCP Server (PID: {pid})...")
        try:
            if PLATFORM == "windows":
                subprocess.run(
                    ["taskkill", "/F", "/T", "/PID", str(pid)],
                    capture_output=True, timeout=10,
                )
            else:
                os.kill(pid, signal.SIGTERM)
                for _ in range(10):
                    if not _is_process_alive(pid):
                        break
                    time.sleep(0.5)
                else:
                    os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
        _remove_mcp_pid()
        ok("MCP Server 已停止")
        return True
    if _is_mcp_running(config):
        warn(f"端口 {config['mcp_port']} 仍有服务，但无 PID 记录")
        _remove_mcp_pid()
        return False
    info("MCP Server 未在运行")
    _remove_mcp_pid()
    return True


def register_claude_mcp(config: dict) -> None:
    section("注册 MCP 到 Claude Code")
    mcp_url = f"http://localhost:{config['mcp_port']}/mcp"
    if not has_command("claude"):
        info(
            f"Claude Code CLI 未检测到，请手动注册:\n"
            f"    {BOLD}claude mcp add penpot -t http {mcp_url}{NC}"
        )
        return
    result = run_cmd(["claude", "mcp", "list"], timeout=10)
    if result.returncode == 0 and result.stdout and "penpot" in result.stdout.lower():
        ok("Claude Code 已注册 penpot MCP")
        return
    result = run_cmd(["claude", "mcp", "add", "penpot", "-t", "http", mcp_url], timeout=10)
    stdout = result.stdout or ""
    if result.returncode == 0 or "Added" in stdout or "already" in stdout:
        ok("已注册到 Claude Code")
    else:
        warn(f"自动注册失败，请手动执行: claude mcp add penpot -t http {mcp_url}")


# ---------------------------------------------------------------------------
# Sub-commands
# ---------------------------------------------------------------------------


def cmd_deploy(config: dict) -> int:
    print(f"\n{CYAN}{BOLD}  Penpot 完整部署 (Docker + MCP){NC}\n")
    if not preflight_check("all"):
        return 1
    if not deploy_penpot(config):
        fail("Penpot 部署失败")
        return 1
    if not start_mcp(config):
        warn("MCP Server 启动异常")
    register_claude_mcp(config)
    return 0


def cmd_mcp_only(config: dict) -> int:
    print(f"\n{CYAN}{BOLD}  Penpot MCP Server 部署{NC}\n")
    if not preflight_check("mcp"):
        return 1
    penpot_base = os.environ.get("PENPOT_BASE_URL", "")
    is_remote = penpot_base and not any(h in penpot_base for h in ("localhost", "127.0.0.1"))
    if is_remote:
        info(f"将连接到远程 Penpot 实例: {penpot_base}")
    elif not _is_penpot_running(config):
        warn(f"Penpot 未在端口 {config['penpot_port']} 运行")
    if not start_mcp(config):
        return 1
    register_claude_mcp(config)
    return 0


def cmd_start(config: dict) -> int:
    print(f"\n{CYAN}{BOLD}  启动 Penpot 服务{NC}\n")
    if not preflight_check("all"):
        return 1
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = docker_compose_cmd()
        if dc_cmd and ensure_docker_running():
            subprocess.run(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"], timeout=120,
            )
    start_mcp(config)
    return 0


def cmd_stop(config: dict) -> int:
    print(f"\n{CYAN}{BOLD}  停止 Penpot 服务{NC}\n")
    section("停止 MCP Server")
    stop_mcp(config)
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        dc_cmd = docker_compose_cmd()
        if dc_cmd:
            section("停止 Penpot (Docker)")
            subprocess.run(
                dc_cmd + ["-f", compose_file, "down"],
                cwd=config["penpot_dir"], timeout=120,
            )
    return 0


def cmd_status(config: dict) -> int:
    print(f"\n{CYAN}{BOLD}  Penpot 服务状态{NC}\n")
    if _is_penpot_running(config):
        ok(f"Penpot Frontend  {DIM}-> http://localhost:{config['penpot_port']}{NC}")
    else:
        fail(f"Penpot Frontend  (端口 {config['penpot_port']} 未监听)")
    if _is_mcp_running(config):
        ok(f"MCP Server       {DIM}-> http://localhost:{config['mcp_port']}/mcp{NC}")
    else:
        fail(f"MCP Server       (端口 {config['mcp_port']} 未监听)")
    if is_port_listening(config["plugin_port"]):
        ok(f"Plugin Server    {DIM}-> http://localhost:{config['plugin_port']}{NC}")
    else:
        info(f"Plugin Server    (端口 {config['plugin_port']} 未监听)")
    print()
    return 0


def cmd_ensure(config: dict) -> int:
    if _is_mcp_running(config):
        print(f"Penpot MCP already running on port {config['mcp_port']}")
        return 0
    compose_file = os.path.join(config["penpot_dir"], "docker-compose.yml")
    if os.path.isfile(compose_file):
        if has_command("docker") and not ensure_docker_running():
            fail("Docker daemon 无法启动")
            return 1
        dc_cmd = docker_compose_cmd()
        if dc_cmd and not _is_penpot_running(config):
            subprocess.run(
                dc_cmd + ["-f", compose_file, "up", "-d"],
                cwd=config["penpot_dir"],
                capture_output=True, timeout=120,
            )
            for _ in range(30):
                if _is_penpot_running(config):
                    break
                time.sleep(1)
    if start_mcp(config):
        return 0
    fail("Penpot MCP not installed. Run: cataforge penpot deploy")
    return 1


# ---------------------------------------------------------------------------
# CLI entry (for use as python -m cataforge.integrations.penpot)
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    import argparse

    ensure_utf8_stdio()
    load_dotenv(set_env=True)

    parser = argparse.ArgumentParser(description="CataForge Penpot integration")
    parser.add_argument(
        "command", nargs="?",
        choices=["deploy", "mcp-only", "start", "stop", "status"],
    )
    parser.add_argument("--ensure", action="store_true")
    args = parser.parse_args(argv)
    config = _get_config()

    if args.ensure:
        return cmd_ensure(config)
    if not args.command:
        parser.print_help()
        return 0
    handlers = {
        "deploy": cmd_deploy, "mcp-only": cmd_mcp_only,
        "start": cmd_start, "stop": cmd_stop, "status": cmd_status,
    }
    return handlers[args.command](config)


if __name__ == "__main__":
    sys.exit(main())
