"""Cursor platform adapter."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from cataforge.adapter.platform.adapter import PlatformAdapter
from cataforge.adapter.platform.helpers import symlink_or_copy
from cataforge.utils.atomic_write import atomic_write_text

if TYPE_CHECKING:
    from cataforge.runtime.deploy.manifest import DeployManifest as DeployManifest


class CursorAdapter(PlatformAdapter):
    @property
    def platform_id(self) -> str:
        return "cursor"

    @property
    def display_name(self) -> str:
        return "Cursor"

    def get_project_root_env_var(self) -> str | None:
        return "CURSOR_PROJECT_DIR"

    def get_agent_scan_dirs(self) -> list[str]:
        # Default: Cursor-native only. The legacy fallback to ``.claude/agents``
        # was removed in the M5 change — only ``scan_dirs[0]`` is ever written
        # during deploy, so listing ``.claude/agents`` as a fallback created
        # the false impression that Cursor deploy would produce artifacts
        # under ``.claude/``. Users who really want ``.claude/agents`` scanned
        # can still declare it explicitly in their profile.yaml.
        return list(self._profile.get("agent_definition", {}).get("scan_dirs", [".cursor/agents"]))

    def get_agent_format(self) -> str:
        return "yaml-frontmatter"

    def deploy_additional_outputs(
        self,
        rules_dir: Path,
        project_root: Path,
        *,
        dry_run: bool = False,
        manifest: DeployManifest | None = None,
        prior_manifest: set[str] | None = None,
    ) -> list[str]:
        return self._generate_mdc_rules(rules_dir, project_root, dry_run=dry_run, manifest=manifest)

    def deploy_rules(
        self,
        source_dir: Path,
        project_root: Path,
        *,
        dry_run: bool = False,
        manifest: DeployManifest | None = None,
        prior_manifest: set[str] | None = None,
        force_copy: bool = False,
    ) -> list[str]:
        """Rule deployment for Cursor.

        The canonical Cursor rule surface is ``.cursor/rules/*.mdc``, which
        is generated by ``deploy_additional_outputs`` elsewhere. This method
        only governs the **optional** Markdown mirror at ``.claude/rules``
        intended for projects that also run Claude Code against the same
        tree and want to share source-of-truth prompts.

        The mirror is **off by default** (as of the M5 change).  Opt in via
        ``rules.cross_platform_mirror: true`` in
        ``.cataforge/platforms/cursor/profile.yaml`` — or a user-level
        ``platforms/cursor/overrides/profile.yaml`` if the registry supports
        overrides on your install.
        """
        rules_cfg = self._profile.get("rules") or {}
        if not bool(rules_cfg.get("cross_platform_mirror", False)):
            if dry_run:
                return [
                    "SKIP: .claude/rules Markdown mirror "
                    "(enable via profile rules.cross_platform_mirror: true)"
                ]
            return []
        actions = symlink_or_copy(
            source_dir,
            project_root / ".claude" / "rules",
            dry_run=dry_run,
            force_copy=force_copy,
        )
        if manifest is not None and not dry_run:
            manifest.record(".claude/rules")
        note = (
            "note: Cursor deploy linked .claude/rules for cross-platform prompt "
            "sharing (profile rules.cross_platform_mirror=true)"
        )
        if dry_run:
            return actions + [note]
        return actions + [note]

    def _generate_mdc_rules(
        self,
        source_dir: Path,
        project_root: Path,
        *,
        dry_run: bool = False,
        manifest: DeployManifest | None = None,
    ) -> list[str]:
        """Generate .cursor/rules/ MDC files from canonical rule sources.

        Only handles ``.cataforge/rules/*.md`` here; override rules under
        ``.cataforge/platforms/cursor/overrides/rules/`` are picked up by
        the base-class ``deploy_overrides_rules`` flow which calls
        :meth:`_wrap_rule_for_platform` (overridden below to produce the
        same MDC + ``alwaysApply`` wrapping).
        """
        output_dir = project_root / ".cursor" / "rules"
        if not dry_run:
            output_dir.mkdir(parents=True, exist_ok=True)

        actions: list[str] = []
        for md_file in sorted(source_dir.glob("*.md")):
            mdc_name = md_file.stem + ".mdc"
            mdc_rel = f".cursor/rules/{mdc_name}"
            if dry_run:
                actions.append(f"would deploy rules/{md_file.name} → .cursor/rules/{mdc_name}")
                continue
            content = md_file.read_text()
            mdc_content = _wrap_as_mdc(md_file.stem, content)
            atomic_write_text(output_dir / mdc_name, mdc_content)
            if manifest is not None:
                manifest.record(mdc_rel)
            actions.append(f"rules/{md_file.name} → .cursor/rules/{mdc_name}")

        return actions

    def _wrap_rule_for_platform(self, name: str, content: str) -> tuple[str, str] | None:
        """Wrap an override rule as a Cursor MDC file with ``alwaysApply``.

        Called by the base-class ``deploy_overrides_rules`` flow for every
        ``.cataforge/platforms/cursor/overrides/rules/*.md`` file (including
        the auto-generated ``auto-*.md`` outputs from hook bridge
        ``apply_degradation``).
        """
        return (f".cursor/rules/{name}.mdc", _wrap_as_mdc(name, content))

    def _mcp_json_path(self, project_root: Path) -> Path:
        return project_root / ".cursor" / "mcp.json"


def _wrap_as_mdc(name: str, content: str) -> str:
    """Wrap Markdown content with MDC frontmatter for Cursor."""
    frontmatter = f"""---
description: "{name} rules"
alwaysApply: true
---
"""
    return frontmatter + content
